haskell/containers

- .travis.yml
We want it to be able to build with 7.10 and head.
> Update .travis.yml per hvr's advice

- Data/Sequence.hs
- benchmarks/Sequence.hs
1. Remove all partial functions and all "impossible" errors.
2. Simplify the way the sequence pieces are put together at the
bottom.
> Clean up <*> some more

- Data/Set/Base.hs
> Minor typo fix in Data.Set.Base

- Data/Sequence.hs
Add `instance IsString (Seq Char)` when compiling with GHC.
> Add IsString instance

- Data/IntSet/Base.hs
- containers.cabal
- tests/intset-strictness.hs
> Removed unnecessary strictness in IntSet.foldl accumulator.

- Data/Graph.hs
- Data/IntMap/Base.hs
- Data/Map/Base.hs
- Data/Sequence.hs
- Data/Tree.hs
NOTE: this also contains two commits already submitted via #168 due to the way GitHub PRs work
> GHC HEAD -Wall cleanups

- Data/Map/Strict.hs
> fix typo in documentation

- Data/Sequence.hs
> Fix performance of Data.Sequence.filter (fixes #176)

- Data/Sequence.hs
- benchmarks/Sequence.hs
Use `BangPatterns` to reduce clutter in `Data.Sequence`.
When partially applying a `Deep`, `Node2`, or `Node3`
constructor in `traverse`, `traverseWithIndex`, and
`applicativeTree`, change arity to avoid boxing sizes.
Benchmarks indicate small but fairly consistent improvements.
> Use bang patterns for Data.Sequence; avoid boxing

- Data/Sequence.hs
Instead of copying the code over, use polymorphic
`traverseWithIndexDigit` and `traverseWithIndexNode`, inlined,
to implement `traverseWithIndexDigitE`, etc. This gives us the
desired specialization with less source code.
> Clean up traverseWithIndex

- Data/Tree.hs
Inspired by [this SO question](http://stackoverflow.com/a/37279548/791604), it seems there's no fold for trees! That's odd.
> add a catamorphism on Trees

- Data/Sequence.hs
- tests/seq-properties.hs
This finishes the indexed folds. Implementing `foldrWithIndex`
using this function gives wretched performance, unfortunately.
It would be nice to know why, and whether anything can be done
about that.
> Add foldMapWithIndex for Data.Sequence

- Data/Map/Base.hs
- Data/Map/Strict.hs
- benchmarks/Map.hs
Also fix alterF documentation formatting.
> Add rewrite rule for alterF with pairs

- Data/Sequence.hs
Export `cycleN` and document its performance.
> Export cycleN

- Data/Sequence.hs
The helper functions now use bang patterns to ensure strictness in their
`Int` arguments.
Use a single unsigned comparison instead of two signed ones
for `adjust` and `index`.
> Make Data.Sequence.adjust helpers stricter

- Data/Sequence.hs
- benchmarks/Sequence.hs
- tests/seq-properties.hs
This is messy, and may remain so, but it would be nice to find
some way to clean it up a bit. Also, we can and should be
more eager about rebuilding and should look for opportunities to
use arithmetic to figure out sizes.
> Add deleteAt to Data.Sequence

- Data/Sequence.hs
- benchmarks/Sequence.hs
Use arithmetic to avoid inspecting nodes and build some things more eagerly.
> Some cleanup of deleteAt

- Data/Sequence.hs
`splitMap` was annoyingly sensitive to any minor change anywhere,
presumably because it was tough on the inliner. Using
`ScopedTypeVariables` when compiling with GHC, we can pull the
splitting function out of the polymorphic recursion. Suddenly
GHC starts unboxing `Int`s and generally acting like a happier
compiler. I'm hopeful that `ScopedTypeVariables` will be in the
next standard so we can eventually drop the other code.
> Use ScopedTypeVariables to optimize zipping

- Data/Sequence.hs
Use safe coercions to avoid `fmap` at the leaves to deal with
`Elem` and at the root to deal with `Seq`. This should speed
things up for non-trivial functors.
> Make traverse fmap less

- Data/Set.hs
- Data/Set/Base.hs
- changelog.md
- tests/set-properties.hs
The set versions are just like the map versions, pretty much.
> Add fromDescList and fromDistinctDescList

- Data/IntMap/Base.hs
- Data/IntMap/Lazy.hs
- Data/IntMap/Strict.hs
- Data/Map/Base.hs
- Data/Map/Lazy.hs
- Data/Map/Strict.hs
- Data/Set/Base.hs
- Data/Utils/StrictMaybe.hs
- changelog.md
- containers.cabal
- tests/intmap-properties.hs
- tests/map-properties.hs
* Add `restrictKeys` and `withoutKeys` to `Data.Map` and
`Data.IntMap`.
* Add tests for the defining properties of these operations.
> Add restrictKeys and withoutKeys

- Data/Set.hs
- Data/Set/Base.hs
- changelog.md
- tests/set-properties.hs
These match the ones just added for maps.
> Add new index-based and unsafe Set functions

- Data/Map/Internal.hs
- Data/Sequence/Internal.hs
- include/containers.h
- tests/seq-properties.hs
* Expose `Data.Sequence` pattern synonyms for real.
* Add tests for the pattern synonyms.
> Actually expose Data.Sequence pattern synonyms

- Data/IntMap/Internal.hs
- Data/Map/Internal.hs
I've implemented a version of `mergeA` (and sundry other applicative functions) for `IntMap`.
> IntMap general merge

- Data/IntMap/Internal.hs
- Data/Map/Internal.hs
Forgot to actually export the new functions.
> Int map general merge

- Data/Sequence/Internal.hs
Add instances of `Eq1`, `Ord1`, `Show1`, and `Read1` for
`Data.Sequence`.
> Add lifted instances for Data.Sequence

- Data/Set/Internal.hs
Add `Eq1`, `Ord1`, and `Show1` instances for `Data.Set`.
> Add instances for Data.Set

- Data/Tree.hs
Add `Eq1`, `Show1`, `Eq1`, and `Ord1` instances for `Data.Tree`.
> Add lifted instances for Data.Tree

- Data/Graph.hs
Add `Generic`, `Generic2`, `Data`, `Eq`, `Show`, `Read`,
`Foldable`, `Traversable`, `Eq1`, `Show1`, `Read1`, and
`Typeable` instances for `Data.Graph.SCC`.
Fixes #51
> Add instances for Data.Graph.SCC

- Data/IntMap/Internal.hs
- Data/Map/Internal.hs
Fixes https://github.com/haskell/containers/issues/349
> Fix typo in error message for minimum

- Data/Sequence/Internal.hs
- Data/Tree.hs
- tests/seq-properties.hs
> Add MonadZip Seq instance

- Data/Graph.hs
- Data/IntMap.hs
- Data/IntMap/Internal.hs
- Data/IntMap/Lazy.hs
- Data/IntMap/Merge/Lazy.hs
- Data/IntMap/Merge/Strict.hs
- Data/IntMap/Strict.hs
- Data/IntSet.hs
- Data/IntSet/Internal.hs
- Data/Map.hs
- Data/Map/Internal.hs
- Data/Map/Lazy.hs
- Data/Map/Lazy/Merge.hs
- Data/Map/Merge/Lazy.hs
- Data/Map/Merge/Strict.hs
- Data/Map/Strict.hs
- Data/Map/Strict/Internal.hs
- Data/Map/Strict/Merge.hs
- Data/Sequence.hs
- Data/Sequence/Internal.hs
- Data/Set.hs
- Data/Set/Internal.hs
- Data/Tree.hs
- Utils/Containers/Internal/BitQueue.hs
- Utils/Containers/Internal/BitUtil.hs
Fixes https://github.com/haskell/containers/issues/389.
> Remove 'stability' annotations

- Data/Sequence/Internal.hs
- tests/Makefile
- tests/seq-properties.hs
* Use a custom `liftA2` implementation for Data.Sequence for
base 4.10.
* Write RULES for `liftA2`.
> Write a liftA2 for Seq

- Data/Graph.hs
- Data/Tree.hs
* Define custom `<$`, `liftA2`, `<*`, and `*>` for `Data.Tree`.
* Use `liftA2` as appropriate in `Data.Tree` and `Data.Graph`.
> LiftA2 some more, etc.

- Data/IntMap/Internal.hs
- Data/Map/Internal.hs
- Data/Map/Strict/Internal.hs
- changelog.md
* liftA2 update for `Data.Map` and `Data.IntMap`.
* Changelog update and fixes.
> liftA2 update for Data.Map and Data.IntMap

- Data/IntMap/Internal.hs
Reverts haskell/containers#408
> Revert "Optimize IntMap's withoutKeys", in order to squash things first (I hope)

- Data/IntMap/Internal.hs
Reverts haskell/containers#410
> Revert "Revert "Optimize IntMap's withoutKeys", in order to squash things first (I hope)"

- Data/Graph.hs
- Data/IntMap/Internal.hs
- Data/IntMap/Merge/Lazy.hs
- Data/IntMap/Merge/Strict.hs
- Data/IntSet/Internal.hs
- Data/Map/Internal.hs
- Data/Map/Merge/Lazy.hs
- Data/Map/Merge/Strict.hs
- Data/Sequence/Internal.hs
- Data/Set/Internal.hs
- Data/Tree.hs
These annotations are based on the changelog and go back to v0.5.4 / GHC-7.8.
> Add @since-annotations

- Utils/Containers/Internal/BitUtil.hs
We used to unbox shifts manually to make sure things inlined
adequately. Based on my benchmarks, that doesn't seem to be
necessary anymore. The differences are small, and for `IntMap`
benchmarks actually seem to favor doing the simple thing.
> Stop hand-unboxing shifts

- Data/Set.hs
- Data/Set/Internal.hs
- changelog.md
- tests/set-properties.hs
Add
* `cartesianProduct :: Set a -> Set b -> Set (a, b)`
* `disjointUnion :: Set a -> Set b -> Set (Either a b)`
>  Add Cartesian products and disjoint unions for Set 

- CONTRIBUTING.md
- README.md
- Link to libraries@haskell.org discussion if applicable
- Run benchmarks and include results
- Add unit tests
Addresses treeowl@s comment in
https://github.com/haskell/containers/pull/455#issuecomment-353204381.
> Update CONTRIBUTING.md with Pull Request guidance.

- Data/Sequence.hs
Several Redditors responded to [my RFC](https://www.reddit.com/r/haskell/comments/7p6eg2/request_for_comments_on_expanded_datasequence_docs/).
Edit the `Data.Sequence` documentation to address most of their concerns.
> Respond to suggestions on Data.Sequence docs

- tests/seq-properties.hs
> test stability of sort and sortOn

- Data/Tree.hs
This partially addresses https://github.com/haskell/containers/issues/495.
> Improve Data.Tree documentation.

- Data/Set/Internal.hs
It is but a tiny typo, but I noticed it and thought I would fix it. Cheers :)
> fix typo disjoin

- Data/Tree.hs
Sorry to submit such a minimal and trivial pull request, but I was just reading the documentation and noticed what looks like a typo, and thought I might as well suggest a correction...
> Correct typo

- Data/Graph.hs
I changed "topologically sorted" to "reverse topologically sorted" (is that even English?) and added examples.
Closes #561
> Data.Graph.stronglyConnComp: document ordering

- containers.cabal
> Update criterion bounds.

- Data/IntMap/Internal.hs
- Data/IntMap/Strict.hs
- Data/Map/Internal.hs
- Data/Map/Strict/Internal.hs
Found by a question in StackOverflow https://stackoverflow.com/questions/52828746/haskell-data-map-strict-alterf-parse-error-on-input/52829097
> Fix sample code of alterF in haddock

- tests/intmap-properties.hs
> Simplify Arbitrary instance for IntMap

- tests/set-properties.hs
> Fix compilation of 'set-properties' test suite with GHC-8.6

- Data/Sequence/Internal.hs
> Update cycleTaking docs

- containers/src/Data/IntMap/Lazy.hs
- containers/src/Data/IntMap/Strict.hs
- containers/src/Data/IntMap/Strict/Internal.hs
- containers/src/Data/IntSet.hs
- containers/src/Data/IntSet/Internal.hs
I replaced all references to that paper. Fixes #655
> fix references to citeseer

- containers-tests/benchmarks/Set.hs
- containers-tests/tests/set-properties.hs
- containers/src/Data/Set.hs
- containers/src/Data/Set/Internal.hs
> Add Data.Set.alterF

- containers-tests/tests/intmap-properties.hs
- containers-tests/tests/map-properties.hs
- containers/src/Data/IntMap/Internal.hs
> IntMap.mergeA: Fix effects sequencing with negative keys

- containers/src/Data/IntMap/Internal.hs
- containers/src/Data/IntMap/Strict/Internal.hs
- containers/src/Data/Map/Internal.hs
- containers/src/Data/Map/Strict/Internal.hs
> Fix haddocks

- .travis.yml
- cabal.haskell-ci
- containers-tests/containers-tests.cabal
- containers/containers.cabal
> Update Travis config with job using GHC 8.8

- containers-tests/tests/intset-properties.hs
- containers/src/Data/IntSet.hs
- containers/src/Data/IntSet/Internal.hs
> Add Data.IntSet.alterF

- containers/src/Data/Sequence/Internal.hs
The extra type information compared to `<*` (cf. similar additions at #713) helps quite a bit. The grouping of arguments feels like it makes sense here, I somehow have less of an itch to change it than with `<*`.
The most error-prone part is to not mix up `pr` and `sf` since they have the same type and play extremely similar roles. That's really the main motivation for invariant 1. Technically, it's necessary to prove a complete specification of `(<*>)`, but if it were not for `pr`/`sf`, I could convince myself the function is correct with only the other invariants about sizes and by trusting parametricity to fill in the gaps.
> Document internals of liftA2

- containers-tests/containers-tests.cabal
- containers/containers.cabal
Add `default-language` field all over the place.
> More Hackage wibbles

- containers/src/Data/Map/Strict/Internal.hs
…as requested in https://github.com/haskell/containers/issues/252#issuecomment-631071812.
> Add since-annotation for Data.Map.Strict.alterF

- containers-tests/tests/Makefile
(this enables `make intset-strictness` and so forth)
> add target for *-strictness tests

- containers/src/Data/IntMap/Internal.hs
- containers/src/Data/IntMap/Lazy.hs
- containers/src/Data/IntMap/Strict.hs
- containers/src/Data/IntMap/Strict/Internal.hs
> Expose IntMap.traverseMaybeWithKey

- containers/src/Data/Set/Internal.hs
in the same way done for Data.Map.difference
> Clarify semantics of Data.Set.difference in Haddock

- containers-tests/containers-tests.cabal
It was actually testing the lazy version
> Fix map-strict-properties

- containers-tests/containers-tests.cabal
- containers-tests/tests/IntMapValidity.hs
- containers-tests/tests/IntSetValidity.hs
- containers-tests/tests/bitqueue-properties.hs
- containers-tests/tests/intmap-properties.hs
- containers-tests/tests/intmap-strictness.hs
- containers-tests/tests/intset-properties.hs
- containers-tests/tests/intset-strictness.hs
- containers-tests/tests/listutils-properties.hs
- containers-tests/tests/map-properties.hs
- containers-tests/tests/map-strictness.hs
- containers-tests/tests/seq-properties.hs
- containers-tests/tests/set-properties.hs
- containers-tests/tests/tree-properties.hs
> Migrate from test-framework to tasty

- containers/docs/sequence.rst
- containers/src/Data/Sequence/Internal.hs
- containers/src/Data/Set/Internal.hs
> fix typos and reword

- .github/workflows/haskell-ci.yml
- cabal.haskell-ci
- containers-tests/benchmarks/IntMap.hs
- containers-tests/benchmarks/IntSet.hs
- containers-tests/benchmarks/LookupGE/IntMap.hs
- containers-tests/benchmarks/LookupGE/Map.hs
- containers-tests/benchmarks/Map.hs
- containers-tests/benchmarks/Sequence.hs
- containers-tests/benchmarks/Set.hs
- containers-tests/benchmarks/SetOperations/SetOperations.hs
- containers-tests/containers-tests.cabal
> Migrate from gauge to tasty-bench

- containers/src/Data/IntMap/Internal.hs
- containers/src/Data/IntMap/Strict/Internal.hs
- containers/src/Data/Map/Internal.hs
- containers/src/Data/Map/Strict/Internal.hs
> Fix/update documentation for `fromListWithKey

- containers-tests/benchmarks/Set.hs
> add benchmarks for Data.Set.powerSet

- CONTRIBUTING.md
- containers/docs/sequence.rst
Hi 😊
I saw the note could be improved in case anyone wants to try the code out in GHCi.
Let me now if this PR could be useful and/or I can improve it in any way.
Have a good day!
> Update docs: note on ghci multiline mode

- containers/src/Data/Set/Internal.hs
In module `Data.Set.Internal` two error messages mention `Data.Map.Internal`.
> Fix error message

- containers/changelog.md
- containers/src/Data/Graph.hs
- containers/src/Data/IntMap/Internal.hs
- containers/src/Data/IntSet/Internal.hs
- containers/src/Data/Map/Internal.hs
- containers/src/Data/Sequence/Internal.hs
- containers/src/Data/Set/Internal.hs
- containers/src/Data/Tree.hs
* Update `CHANGELOG.md`.
* Add missing `@since` annotations.
Closes #911.
> Update changelog and @since annotations

- containers/docs/map.rst
- containers/docs/sequence.rst
- containers/docs/set.rst
> Update links for the `OverloadedLists` extension

- containers-tests/tests/tree-properties.hs
- containers/src/Data/Tree.hs
* Test that last is lazy enough to only look at the path down to the last leaf
* Test that foldMap and foldMap1 fold according to the structure of the tree
Closes #924
> More foldMap related Tree tests

- .github/workflows/haskell-ci.yml
- containers-tests/containers-tests.cabal
- containers/changelog.md
- containers/containers.cabal
- containers/src/Data/IntSet/Internal.hs
> Bump version to 0.7

- containers/src/Data/Graph.hs
Should address https://github.com/haskell/containers/pull/953#discussion_r1257348718
> Move pattern synonym under cpp guard

- containers/changelog.md
- containers/src/Data/Map/Internal.hs
> Fix changelog for v0.6.6 and v0.6.8

- containers/changelog.md
> Fix contributor name

- containers/src/Data/IntMap/Internal.hs
- containers/src/Data/IntSet/Internal.hs
- containers/src/Data/Map/Internal.hs
- containers/src/Data/Sequence/Internal.hs
- containers/src/Data/Set/Internal.hs
Add Haddocks showing the definitions of (<>) and mempty.
> Document Semigroup and Monoid instances

- containers-tests/benchmarks/IntSet.hs
- containers-tests/tests/intset-properties.hs
- containers/changelog.md
- containers/src/Data/IntSet.hs
- containers/src/Data/IntSet/Internal.hs
> Add foldMap for IntSet

- containers-tests/benchmarks/Set.hs
> Reduce the Set.powerSet benchmark sizes

- .github/workflows/mhs-ci.yml
- containers/include/containers.h
What the title says.
Also, update CI to use mcabal for building the package.
> MicroHs has pattern synonyms now

- containers/src/Data/Graph.hs
DEFINE_PATTERN_SYNONYMS is set for GHC and MicroHs.
Related: #1081
> Guard CyclicSCC with DEFINE_PATTERN_SYNONYMS

- .readthedocs.yml
> Fix the ReadTheDocs config

- containers/src/Data/IntMap/Strict/Internal.hs
- containers/src/Data/IntSet/Internal.hs
- containers/src/Data/Map/Internal.hs
- containers/src/Data/Map/Strict/Internal.hs
- containers/src/Data/Sequence/Internal.hs
- containers/src/Data/Set/Internal.hs
I'm assuming this is the page that the link originally referred to since the link now redirects to a different page.
> copy the updated references from the public to the internal modules

- containers/src/Data/IntMap/Internal.hs
- containers/src/Data/IntSet/Internal.hs
- containers/src/Data/IntSet/Internal/IntTreeCommons.hs
* mask: Now creates the Prefix, skipping some unnecessary operations
* branchMask: Shift the high bit right instead of the low bit left
* branchPrefix: New function to directly create a Prefix instead of going via mask.
The performance improvements appear to be too small to show up in benchmarks, but these changes also make the code nicer.
> Improve some Int{Map,Set} bitwise ops

- containers/src/Data/IntMap/Internal.hs
- containers/src/Data/IntSet/Internal.hs
> Call out that Int{Set,Map}.size are not O(1)
