haskell/containers

include/containers.h
Guess the base library version based on `__GLASGOW_HASKELL__`
when compiling without Cabal.
=> Improve MIN_VERSION_base fall-back

Data/IntMap/Base.hs, Data/IntSet/Base.hs, Data/Map/Base.hs, Data/Sequence.hs, Data/Set/Base.hs
Admittedly, the CPP isn't pretty but writing the code in this way makes the code future proof
See ekmett/semigroups#56 for more details
=> Semigroup instances

Data/Sequence.hs
Lean a bit harder on the type system to ensure that the
reversing function is called everywhere it's supposed
to be. Yes, this should all be covered by the test suite
anyway, but it can't hurt.
=> Make reverse helpers polymorphic

Data/Sequence.hs, containers.cabal, tests/seq-properties.hs
Hack Milan's `mapWithIndex` into `traverseWithIndex`.
Add `default ()` to make sure we never accidentally use defaulting.
=> Add traverseWithIndex

Data/IntMap.hs
the URL in the current version is broken (or paywalled)
=> repair broken URL in IntMap documentation

Data/IntMap/Base.hs, Data/IntSet/Base.hs, Data/Map/Base.hs, Data/Set/Base.hs
we want Generics for everything (otherwise we can't derive Generics for any data types which contain these without creating orphan instances)
the end-goal is to have all of these: https://gist.github.com/kuk0/92fff1c91c526ffb0a9e
and be able to derive instances for e.g. TextShow or Text.PrettyPrint.Generic.Pretty
=> add Generics instance for Map, Set, IntMap, and IntSet

Data/Map/Base.hs, Data/Set/Base.hs
As we no longer use (<=) comparison but use (<) comparison instead since [this commit](https://github.com/haskell/containers/commit/4193a09336772748bdec0cdab5da4257d224c814),
the document is not correct to explain the current implementation.
There's one thing I'm not quite sure of. Anybody agrees that I could remove the following sentence as well?
```
Quickcheck (on [difference]) showed that this was necessary in order
to maintain the invariants. It is quite unsatisfactory that I haven't
been able to find out why this is actually the case! Fortunately, it
doesn't hurt to be a bit more conservative.
```
This is bothering me as
1. the doc might have referred to the problem which was [fixed later](https://github.com/haskell/containers/commit/5f2e1f8e4e6966ac41066d04624991ae81a7eb55) with …
=> Remove wrong document in {Set, Map}.hs related to key comparison

.gitignore, Data/Sequence.hs, tests/seq-properties.hs
Rename the `FingerTree` constructor from `Empty` to `EmptyT`.
Add pattern synonyms `Empty`, `:<|`, and `:|>` to inspect and construct sequences.
=> Sequence pattern synonyms

Data/Tree.hs, changelog.md
Unlike the other container types, `Data.Tree.Tree` is fully
exposed. Therefore, we can and should derive `Generic` and
`Generic1` instances for it.
=> Derive Generic and Generic1 for Data.Tree

Data/IntMap/Base.hs, Data/IntSet/Base.hs, Data/Map/Base.hs, Data/Set/Base.hs
Reverts haskell/containers#184
In #195, Andres Löh argues that these instances should not have been added. I think we should, therefore, revert them unless @kuk0 provides a more convincing demonstration that they are really a good idea.
=> Revert "add Generics instance for Map, Set, IntMap, and IntSet"

Data/Sequence.hs, changelog.md, tests/seq-properties.hs
`intersperse` is just like the one in `Data.List`. It is
implemented using `<**>` for near-optimal performance.
=> Add intersperse for sequences

Data/IntSet/Base.hs, include/containers.h
Also remove some `case` expressions in favor of argument
patterns.
Remove strictness CPP macros from `containers.h`.
=> Use BangPatterns to clean up Data.IntSet

Data/Map.hs, Data/Map/Base.hs, Data/Map/Strict.hs, Data/Set/Base.hs, Data/Tree.hs, changelog.md, containers.cabal
We no longer make any effort whatsoever to support any
version of nhc98 or any version of GHC before 7.0. We
cannot properly support implementations our continuous
integration does not test, and these ones are fairly
rare.
Bump version number
=> Remove all support for nhc98 and GHC <7

Data/Map/Base.hs, Data/Map/Strict.hs
Previously, `adjustWithKey` was implemented using `updateWithKey`.
`updateWithKey` needs to rebalance as it builds the result tree.
`adjustWithKey` never changes the shape of the tree, so
rebalancing on the way up is a waste of time.
=> Speed up adjust and adjustWithKey

Data/IntMap/Base.hs, Data/IntMap/Strict.hs
`delete`, `alter`, `update`, etc., used a `bin` smart
constructor to avoid installing any non-root `Nil`s. Now only
the ones that could have become `Nil` are checked, which is
a good bit cheaper since they're in cache. `adjustWithKey`
was implemented using `updateWithKey`, but in fact it never
needs to worry about `Nil`s, so implementing it directly
eliminates all such checks.
Make `updateLookupWithKey` in `Data.IntMap.Lazy` strict in its
recursive call to avoid essentially useless lazy pair allocation.
=> Speed up IntMap

Data/Map/Base.hs, changelog.md
Lots of functions in `Data.Map.Base` used lazy pairs and such for no obviously good
reason. As a result, they sometimes did strange things like
building up chains of suspensions to rebuild trees.
=> Remove a bunch of unnecessary laziness from Data.Map

Data/Sequence.hs, Data/Utils/BitQueue.hs, changelog.md, tests/bitqueue-properties.hs
Previously, `splitAt` returned a lazy pair, and was pretty much
lazy throughout. Now it's about as strict as it's allowed to be.
Avoid allocating anything extra when splitting at or before the
beginning of a sequence.
Fix misplaced bang annotation (my fault).
Hand-inline and reduce the splitting of the top of the tree. This
avoids a separate cons step at the end, saving some time when
splitting small sequences. This is particularly helpful for
zip performance.
Note: `zip` performance is, for some reason, rather sensitive to
how the inliner handles `sdeepL`. I don't know why. I also don't
really know how to fix it. Splitting in general is rather complicated
and hard to follow. It would be nice to fix that.
=> Speed up Data.Sequence.splitAt and zipWith

Data/IntMap/Base.hs
This isn't (yet) standard, and we don't absolutely need it.
It is nice, however, to be able to give the type signature it
enables, so we can use it when compiling with GHC.
=> Only use ScopedTypeVariables for GHC

containers.cabal
Use `other-extensions` to indicate this. I'm not convinced it's
worth the trouble to try to get real specific about what
extensions we use for each GHC version.
=> Let Cabal know that we use CPP and BangPatterns

Data/Map/Strict.hs, changelog.md
Previously, `Data.Map.Strict` re-exported `traverseWithKey`
from `Data.Map.Base`. That function could produce a map containing
bottoms.
=> Make Data.Map.Strict.traverseWithKey strict enough

Data/Sequence.hs, changelog.md
Add rules fusing `fmap f . reverse` and `reverse . fmap f`
for `Data.Sequence`. These make mapping over a sequence and
reversing it simultaneously as cheap as just mapping over it.
Closes #238.
=> Fuse fmap with reverse for Data.Sequence

.gitignore, Data/Sequence.hs
Rewrite `splitAt`, `take`, and `drop` helper functions to build full results
instead of returning pieces, and to build their results eagerly, instead of
(unnecessarily) suspending them lazily. This has a major impact on performance.
GHC specialization can't help us, because we're now treating the top layer of
the tree differently in every helper. As a result, there's a lot of source
code, but that's our problem.
Benchmark results, compared to containers 0.5.7.1:
Old: benchmarking splitAt/append/10
time                 1.950 ms   (1.946 ms .. 1.954 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 1.952 ms   (1.949 ms .. 1.958 ms)
std dev             53 12.41 μs   (7.154 μs .. 19.01 μs)
New: benchmarking splitAt/append/10
time                 1.056 ms   (1.050 ms .. 1.065 ms) …
=> Speed up sequence splitting and zipping some more

Data/Sequence.hs, tests/seq-properties.hs
Break up a sequence into pieces of a given size. Based on
`Data.List.Split.chunksOf` and implemented using `splitMap`.
=> Add chunksOf to Data.Sequence

Data/Map/Base.hs
The strict `alterF` rewrite target for `(,) b` was too strict.
I *think* it now has the correct semantics.
=> Fix strictness of alterF rewrite target

tests/map-strictness.hs
The `Arbitrary (Map k v)` had a totally redundant `Eq k`
constraint for some reason.
=> Remove redundant Eq constraint

Data/Sequence.hs
A couple years ago I thought it *must* be a good idea to ever look down
the middle if it could possibly be avoided, but I never had any
benchmarks to support it, and it seems pretty silly in retrospect.
Reverting pending some numbers demonstrating it's really the way to go.
=> Stop fearing the middle

Data/Sequence.hs
`splitAt'` wasn't really doing anything good, and certainly
wasn't worth the extra source code.
=> Nix splitAt'

Data/Sequence.hs
This one's all about making nice to GHC by pulling
local functions to the top level and marking them
inline, as well as eta-expanding at a recursive
call site.
Also, use pattern matching more in the definition of `splitAt`.
Old (after recent `splitAt` improvements):
benchmarking zip/ix10000/5000
time                 8.806 μs   (8.768 μs .. 8.857 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 8.787 μs   (8.766 μs .. 8.879 μs)
std dev              113.3 ns   (30.31 ns .. 244.0 ns)
benchmarking zip/nf100
time                 13.19 μs   (13.15 μs .. 13.24 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 13.19 μs   (13.15 μs .. 13.28 μs)
std dev              157.8 ns   (86.36 ns .. 288.1 ns)
benchmarking zip/nf10000
time                 1.768 ms   (1.764 ms .. 1.774 ms) …
=> Speed up zipWith some more

tests/bitqueue-properties.hs, tests/intmap-strictness.hs, tests/intset-strictness.hs, tests/map-strictness.hs
Use `Text.Show.Functions` (blech!) to avoid declaring our own,
similar instances and using `FlexibleInstances` to do so (double
blech!). Remove unused invocation of `GeneralizedNewtypeDeriving`.
I had planned to add the necessary extensions to the Cabal file, but they weren't necessary!
=> Remove unnecessary extensions from tests

tests/deprecated-properties.hs, tests/intmap-properties.hs, tests/intmap-strictness.hs, tests/map-properties.hs, tests/map-strictness.hs
Previously, a number of tests used functions directly as
arguments to QuickCheck properties. As a result, they needed
to include the horrifying `Text.Show.Functions`.
Now the properties requiring functions use
`Test.QuickCheck.Function.Fun`, which has both a meaningful
`Show` instance and proper shrinks.
=> Use QuickCheck function support

Data/IntMap/Base.hs, Data/IntMap/Lazy.hs, Data/IntMap/Strict.hs, Data/Sequence.hs, changelog.md
The implementation is just taken from `Control.Lens.At`, because
`IntMap` lookup is so fast there's no point in trying to be clever
about it.
Clear up unused-binding warning in `Data.Sequence`.
=> Add alterF for Data.IntMap

Data/Sequence.hs, changelog.md, tests/seq-properties.hs
Also improve the QuickCheck properties for `chunksOf` and
`insertAt`, and add pattern synonym documentation.
=> Add lookup and (!?) to Data.Sequence

Data/Sequence.hs, changelog.md, tests/seq-properties.hs
Make cycleTaking more tolerant of edge cases to match
list equivalent. Add QuickCheck property.
=> Rename cycleN to cycleTaking

Data/Sequence.hs, benchmarks/Sequence.hs
Make `insertAt` rebuild the tree eagerly, which saves a little
time and avoids the possibility that large thunks will build
up at the root of the tree when multiple elements are inserted.
For long sequences `insertAt` is around 4.6 times as fast as
splitting the sequence and re-forming it around the new element.
=> Add insertAt benchmark

Data/IntMap/Strict.hs, Data/Sequence.hs, benchmarks/Sequence.hs
Previously, `adjust` would place a thunk at the top of the tree.
Now, it pushes that thunk all the way down to the appropriate
leaf. This way, performing multiple adjustments to different
locations will not lead to a thunk clog at the top. The implementation
makes use of a new `MaybeForce` class, which allows `Node`s
(which can by forced safely) and `Elem`s (which generally aren't
allowed to be forced) to be handled in a uniform fashion. I'm
hopeful that `MaybeForce` will prove useful elsewhere in the module
as well.
Adjusting the *same* location many times, however, can lead to
a thunk clog at the leaf. This is generally unavoidable. `update`
used to be implemented as
```haskell
update i x = adjust (const x) i
```
which is subject to the thunk clog problem. By implementing the
`Elem` …
=> Sequences: strictify adjust; reimplement update

Data/Sequence.hs
Previously, `intersperse` would fail if passed a sequence of
length
```haskell
((maxBound :: Int) `quot` 2) + 1
```
Now it should be able to produce results of lengths right up to
`maxBound :: Int`.
=> Make `intersperse` work right up to the edge

Data/Sequence.hs
Previously, `><` only built the top of the tree,
leaving the rest suspended lazily. Now it rebuilds
eagerly, using the full time allocated to it. The
improvements on the `splitAt/append` benchmark are
modest but meaningful. More importantly, it should no
longer be possible to use `><` to produce large chains
of thunks.
Fixes #274
Old: benchmarking splitAt/append/10
time                 1.056 ms   (1.050 ms .. 1.065 ms)
0.995 R²   (0.983 R² .. 1.000 R²)
mean                 1.073 ms   (1.057 ms .. 1.147 ms)
std dev              97.06 μs   (9.638 μs .. 221.7 μs)
variance introduced by outliers: 68% (severely inflated)
New: benchmarking splitAt/append/10
time                 987.8 μs   (982.7 μs .. 992.3 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean                 995.5 μs   (994.6 μs .. 997.2 …
=> Make >< build its result eagerly

Data/Sequence.hs, benchmarks/Sequence.hs, changelog.md, tests/seq-properties.hs
Writing `foldl'` and `foldr'` for sequences by hand, instead of using the
default definitions, makes them about twice as fast.
=> Write custom strict folds

Data/Sequence.hs, benchmarks/Sequence.hs
Also make `partition` build things much more eagerly.
Generally, there's no reason to be lazy in a consing accumulation that's guaranteed single-threaded.
=> Be more eager about building by consing

Data/Tree.hs
The old version assumed that all `String` values in the `Tree` would not contain newlines. The presence of newlines in a `String` value would cause the rendering to break indentation and make even medium sized trees indecipherable.
This minor change allows a `Tree` containing `String`s with newlines to be rendered with the hierarchical indentation preserved. 
Consider the example type `T`:
```
data T = T
instance Show T where
show _ = "Top line\nBottom line"
```
Consider also the following `Tree T` construction and rendering: 
putStr . drawTree $
show <$> Node T [Node T [Node T [], Node T [Node T []], Node T []], Node T [Node T []]]
```
Top line
Bottom line
|
+- Top line
Bottom line
|  |
|  +- Top line
Bottom line
|  |
|  +- Top line
Bottom line
|  |  |
|  |  `- Top line
Bottom line
|  | …
```
=> Corrected drawTree & drawForest to render multiline String values in a palatable manner!

Data/Sequence.hs, benchmarks/Sequence.hs, changelog.md
`fromList` previously suspended most of its work,
storing the structure in thunks rather than trees.
Now it builds everything.
Old:
benchmarking fromList/10
time                 175.2 ns   (174.7 ns .. 175.7 ns)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 175.2 ns   (174.8 ns .. 175.6 ns)
std dev              1.383 ns   (1.124 ns .. 1.775 ns)
benchmarking fromList/100
time                 2.712 μs   (2.707 μs .. 2.720 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.732 μs   (2.717 μs .. 2.779 μs)
std dev              76.64 ns   (40.38 ns .. 147.1 ns)
variance introduced by outliers: 35% (moderately inflated)
benchmarking fromList/1000
time                 32.24 μs   (32.18 μs .. 32.33 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 32.26 μs   (32.22 μs …
=> Make Data.Sequence.fromList more eager

Data/IntMap/Base.hs, Data/IntSet/Base.hs, Data/Map/Base.hs, Data/Sequence.hs, Data/Set/Base.hs, Data/Tree.hs, changelog.md, include/containers.h
* Remove gunk apparently intended to support `Typeable` for
Hugs.
* Derive `Generic` and `Generic1` for `Data.Sequence.ViewL`
and `Data.Sequence.ViewR`.
=> Clean up Typeable; derive more Generic

Data/Sequence.hs, changelog.md
* Add `adjust'`, which forces the new value before installing it
in the sequence.
* Improve the documentation for `lookup`.
* Cut out some unnecessary code from `traverse`.
=> Add Data.Sequence.adjust'

Data/Map/Base.hs, Data/Map/Lazy.hs, Data/Map/Strict.hs, changelog.md, tests/map-properties.hs
Add functions to convert descending lists to maps.
=> Add fromDesc functions for Data.Map

Data/Sequence.hs
The CPP required to support pattern synonyms with earlier GHC
versions produces too much clutter. It's bad enough having to
deal with exports with and without testing and with and without
pattern synonyms. Having two different export mechanisms goes too
far. If users demand support very strenuously, we can put some of
it back. Until then, I don't want to commit to supporting it
indefinitely.
Fixes #297
=> Define pattern synonyms only for GHC >=8

Data/Map/Base.hs, Data/Map/Strict.hs, benchmarks/Map.hs, changelog.md
Previously, `<$` would fill a map with thunks. Rewriting
`map` so it can inline fixes this. Defined a custom `<$` anyway.
Fixes #300
=> Inline Map.map; define Map <$

Data/IntMap/Base.hs, Data/IntMap/Strict.hs
Previously, mapping a constant function would fill an `IntMap`
with thunks.
=> Rewrite IntMap map so it can inline; define <$

Data/IntMap/Base.hs, Data/Map/Base.hs
Accidentally defined a separate `(<$)` function for `Data.Map`.
=> Actually define the (<$) method

.gitignore, Data/IntMap/Base.hs, Data/Map/Base.hs, Data/Map/Strict.hs, Data/Set/Base.hs, Data/Utils/StrictMaybe.hs, changelog.md
Replace hedge algorithms with divide and conquer algorithms for unions,
intersections, differences, and merges in `Data.Set` and `Data.Map`. The
divide and conquer algorithms
* are much simpler,
* have recently been proven asymptotically optimal, and
* are faster on most benchmarks, sometimes much faster, and never
much slower.
=> Stop using hedge algorithms

Data/Set/Base.hs, Data/Utils/PtrEquality.hs, containers.cabal
Use pointer equality to avoid allocating new copies of existing
structures. This helps a number of benchmarks a *lot*. Unfortunately,
it hurts some others a little.
=> Use pointer equality to enhance sharing for Sets

Data/Utils/PtrEquality.hs
Edward Kmett says it's better to do that and take the load off
core-to-core. Currently, that gets shifted to codegen, I think.
=> Use isTrue# for pointer equality

Data/Map/Base.hs, Data/Map/Strict.hs, Data/Set/Base.hs, Data/Utils/PtrEquality.hs, containers.cabal, tests/map-properties.hs, tests/set-properties.hs
Rewrite `unionWith`, `intersectionWithKey`, etc., as independent
functions. Writing either in terms of the other leads to closures
being allocated with extra indirection for the passed function.
`mergeWithKey` misses singleton optimizations for unions. For the
rest, I think `mergeWithKey` is hard to understand, and it's not
immediately obvious how the parts are supposed to fit together.
Since it's used only to reduce *source* code size, and not actual
*generated* code size, I'd rather avoid it for the most part.
I've left `differenceWith` and `differenceWithKey` alone, as they
appear to be rather deeply tied to the concepts in `mergeWithKey`.
=> Continue to improve map functions

Data/Map/Base.hs, Data/Map/Strict.hs, Data/Utils/PtrEquality.hs
Just name shadowing and unused binding nonsense.
=> Kill a bunch of silly warnings.

Data/Map/Base.hs, Data/Map/Lazy.hs, Data/Map/Strict.hs, Data/Map/Strict/Internal.hs, tests/map-properties.hs
* Offer `take`, `drop`, and `splitAt` by index.
* Offer 'takeWhileAntitone`, `dropWhileAntitone`, and `spanAntitone`.
=> Add more indexed and unsafe functions for Data.Map

Data/Map.hs, Data/Map/Base.hs, changelog.md
* `Data.Map` has had several functions documented as deprecated,
but without actual `DEPRECATED` pragmas, for years. Add the
pragmas so we can move toward removal in a couple more major
versions.
* The `showTree` and `showTreeWith` functions don't seem like a
good fit for the public API. I'm deprecating them, but they will
remain available for the foreseeable future in `Data.Map.Base`
or some other internal module.
=> Deprecate some functions in Data.Map

Data/Map/Internal.hs, Data/Map/Strict/Internal.hs, Data/Set/Internal.hs, Utils/Containers/Internal/StrictPair.hs
* `Data.Map.fromDistinctAscList` and `fromDistinctDescList`
were accumulating thunks for no good reason. Make them
build their structures eagerly. This cuts time by a good
bit (a third, maybe).
* Make the same functions in `Data.Set` just a tad more eager
as well.
=> Make Data.Map.fromDistinct{Asc,Desc}List eager

Data/Map/Internal.hs
Implementing the lazy version of `fromAscList` in terms of
`fromAscListWithKey` leaks memory if there are many repeated
keys. Inlining `fromAscListWithKey` into `fromAscList` manually
should fix this. The same goes for `fromDescList`.
=> Implement fromAscList independently

Data/Map/Lazy/Merge.hs, Data/Map/Merge/Lazy.hs, Data/Map/Merge/Strict.hs, Data/Map/Strict/Merge.hs, containers.cabal, tests/map-properties.hs
I think it's more consistent with the rest of the API to name
them `Data.Map.Merge.Lazy` and `Data.Map.Merge.Strict`. This also
gives us the option to add further merge-related modules in the
`Merge` hierarchy. The original names still work for now, but they
are deprecated and hidden from Haddock.
=> Rename merge modules

Data/Map/Internal.hs, Data/Map/Lazy.hs, Data/Map/Strict.hs, Data/Map/Strict/Internal.hs, Data/Set.hs, Data/Set/Internal.hs, changelog.md, tests/map-properties.hs, tests/set-properties.hs
* The `deleteFindMin` and `deleteFindMax` functions are partial,
and also rather ugly. Reimplement `minView`, `minViewWithKey`,
`glue`, etc., using total functions. This produces pretty
core as well.
* Add `lookupMin` and `lookupMax`, total versions of `findMin`
and `findMax`.
=> Quit using deleteFindMin and deleteFindMax

Data/Sequence/Internal.hs
There was a mixture of `#ifdef TESTING` and `#if TESTING`. The later
works, but is not really correct. GHC HEAD now has a `-Wcpp-undef`
warning that we would like to turn on and hence need this fixed.
=> Data.Sequence.Internal: Fix CPP usage

Data/IntMap/Internal.hs
Add `Eq1`, `Ord1`, `Show1`, and `Read1` instances for
`Data.IntMap`. The `Eq1` instance was written by
David Feuer; the rest were written by Oleg Grenrus.
=> Add lifted instances for Data.IntMap

Data/Map/Internal.hs
Switch from `#if` to `#ifdef` on conditionally defined values.
=> Data.Map.Internal: Fix CPP usage

Data/Sequence/Internal.hs
It's partial, and was used in a silly way for no particularly
good reason. We still need a partial function, but we can write
it where we use it.
=> Kill getSingleton

Data/Tree.hs
The `Read1` and `Show1` instances for `Tree` don't take into account the precedence argument, causing them to disagree with the `Read` and `Show` instances for some inputs.
Fixes #380.
=> Fix Read1 and Show1 instances for Tree

Data/IntMap/Internal.hs, Data/IntMap/Merge/Lazy.hs, Data/IntMap/Merge/Strict.hs, Data/Map/Internal.hs, Data/Map/Lazy.hs, Data/Map/Merge/Lazy.hs, Data/Map/Merge/Strict.hs, Data/Map/Strict.hs, Data/Map/Strict/Internal.hs
We had a bunch of stale links to `Strict.Merge` and `Lazy.Merge`.
Fix them all, hopefully.
=> Retarget Haddocks to point to new merge modules

Data/IntMap/Internal.hs, tests/intmap-properties.hs
`restrictKeys` and `withoutKeys` for `Data.IntMap` were completely
wrong. The QuickCheck properties that should have caught this were
never actually run.
* Fix the implementations
* Make the tests actually run.
Fixes #392
=> Fix buggy restrictKeys and withoutKeys

Data/IntMap/Internal.hs, tests/intmap-properties.hs
Optimize IntMap's `withoutKeys` and `restrictKeys`.
Fixes #394
=> Optimize withoutKeys and restrictKeys for IntMap

Data/IntMap/Internal.hs, tests/intmap-properties.hs
The previous PR #400 only optimized `IntMap`'s `restrictKeys` by the time it got pulled in. This PR handles `withoutKeys` using the same algorithm.
Fixes #394
=> Optimize IntMap's withoutKeys

Data/IntMap/Strict.hs, Data/Map/Strict/Internal.hs, changelog.md
* `Data.IntMap.Strict` previously re-exported the lazy `traverseWithKey`.
Implement a strict one.
* `Data.IntMap.Strict` and `Data.Map.Strict` previously had a number of
rewrite rules with strictness bugs. Remove `map/coerce` rules from
each and fix the other rules.
=> Fix lots of strictness bugs

Data/IntMap/Internal.hs, Data/IntMap/Internal/Debug.hs, Data/IntMap/Internal/DeprecatedDebug.hs, Data/IntMap/Lazy.hs, Data/IntMap/Strict.hs, containers.cabal, tests/intmap-properties.hs
Export deprecated copies from the places we don't want them,
and non-deprecated originals from internal places we do
want them. This allows the test suite to run without warnings,
and gives users a way to avoid them when using these functions.
=> Fix up IntMap showTree deprecation story

Data/Map/Internal.hs, Data/Set/Internal.hs
The new pointer equality version of `insert` in `Data.Map` led to
a severe regression in the `last-piece` benchmark of `nofib`.
It turned out that worker/wrapper was doing absolutely horrible
things to `insert`, breaking the pointer equality tests and
also leading to completely unnecessary allocation. This commit
adds horrible hacks that seem to prevent this from happening.
=> Fix insert worker/wrapper issues

Data/Map/Internal.hs, Data/Set/Internal.hs
Give `insertR` the same treatment as `insert` to keep worker/wrapper from throwing away sharing.
=> Defeat worker/wrapper in insertR too

Data/IntMap/Internal.hs, Data/IntSet/Internal.hs, tests/intmap-properties.hs, tests/intset-properties.hs
fixes #414 
informal benchmark:
```haskell
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE CPP          #-}
import           Criterion.Main
import           Data.Bits
import qualified Data.IntMap.Internal as II
import qualified Data.IntMap.Strict   as I
import qualified Data.IntSet          as IS
import qualified Data.IntSet.Internal as ISI
bitcount :: Int -> Word -> Int
#if MIN_VERSION_base(4,5,0)
bitcount a x = a + popCount x
#else
bitcount a0 x0 = go a0 x0
where go a 0 = a
go a x = go (a + 1) (x .&. (x-1))
#endif
datum :: I.IntMap Int
datum = I.fromList (zip [1..10000] [0..])
datum_is :: IS.IntSet
datum_is = IS.fromList [0,3..1000000]
size_tailish :: I.IntMap a -> Int
size_tailish = go 0
where
go !acc (II.Bin _ _ l r) = go (go acc l) r
go acc (II.Tip _ _) = 1 + acc
go acc II.Nil = acc …
```
=> faster {IntMap,IntSet} size functions

Data/IntSet/Internal.hs, Data/Map/Internal.hs, Data/Map/Strict/Internal.hs, Data/Set/Internal.hs
Currently, these aliases are referenced in the Haddocks for the `*.Internal` modules, but because they're not exported, you can't easily see what they represent without digging into the source code. At the very least, we can also export them from the `*.Internal` modules as well.
=> Expose Size (and other Int aliases) from *.Internal modules

containers.cabal
=> Fix -Wmissing-home-modules warnings

Data/Map/Internal.hs
I think this examples would helped me to spot (I tried Ctrl+F with `intersect`).
EDIT: also fixed markup
---
For dual `(set, map) -> set` operations I'd use `union`, `intersection` and `difference` names with some prefix or suffix, as all three are possible. `unionWithMap` etc doesn't sound too bad, does it?
```haskell
unionWithMap        :: Set k -> Map k a -> Set k
intersectionWithMap :: Set k -> Map k a -> Set k
differenceWithMap   :: Set k -> Map k a -> Set k
```
=> Add restictKeys example via intersect, also withoutKeys

Data/IntMap/Internal.hs, Data/IntMap/Lazy.hs, Data/IntMap/Strict.hs, tests/intmap-properties.hs, tests/intmap-strictness.hs
This operator was added to Data.Map but was accidentally left out of the IntMap
API.
```
(!?) :: IntMap a -> Key -> Maybe a
```
See https://github.com/haskell/containers/issues/453 for more information.
=> Add operator IntMap.!?.

Data/Sequence/Internal.hs
When the index is out of bounds mention which function is causing the error. We include the index `i` in the error message because it may be useful in debugging (-1 vs large number could narrow down where to look).
This was originally mentioned in https://github.com/haskell/containers/issues/347.
=> Improve error message for `index`

.travis.yml, Data/Tree.hs, changelog.md, containers.cabal, tests/tree-properties.hs
This is based on an instance for a somewhat more general type
by G. Allais.
See [MonadTree.hs](https://gist.github.com/gallais/4c59b949c743c0a85cab55dcb73aaf7c).
=> Add MonadFix instance for Data.Tree

CONTRIBUTING.md
This includes instructions for building and running benchmarks with both cabal-install and stack.
This addresses #354 and #371.
=> Update CONTRIBUTING.md with benchmark instructions

CONTRIBUTING.md, stack.yaml
Running `stack init` fails if you're using a resolver newer than lts-7.24 because ChasingBottoms has not been in Stackage LTS releases since then. Since Stack is a common workflow people use we should support the most recent Stackage LTS versions out of the box.
In the stack.yaml file we add ChasingBottoms-1.3.1.3 as an extra-dep and default the resolver to 9.20 because lts-10.0 uses GHC 8.2 which is not supported all of the tools yet; ghc-mod is lacking support, for example. Once all tooling supports lts-10.0 we'll change the default resolver.
This also updates CONTRIBUTING.md, removing the `stack init` step because it is no longer needed.
This resolves #458.
=> Add stack.yaml file

Data/Set.hs, Data/Set/Internal.hs, changelog.md, tests/set-properties.hs
This should be somewhat more efficient than what can be written
using the public API because it can glue trees together without
needing to perform a full divide-and-conquer union
Addresses #442
=> Add powerSet to Data.Set

Data/IntMap/Internal.hs, Data/IntSet/Internal.hs, Data/Map/Internal.hs, Data/Map/Strict/Internal.hs, Data/Sequence/Internal.hs, Data/Set/Internal.hs
Let Haddock know that it shouldn't consider the `Internal` modules
home for any identifiers. This should've been done when I exposed
those internal modules. Whoops.
=> Mark Internal modules not-home

Data/Sequence.hs, Data/Sequence/Internal.hs, changelog.md
Make `replicateM` a synonym for `replicateA` for `base >= 4.8.0`.
=> Update replicateM post-AMP

Data/Sequence/Internal.hs, changelog.md
When I originally added an `IsString` instance for `Seq`, we
conservatively used
```haskell
instance IsString (Seq Char)
```
to allow for the possibility that we might eventually want to write
additional instances. But the result is very bad inference and
a discrepency with the instance for lists. So let's not do that.
=> Improve inference for IsString instance for Seq

Data/Sequence.hs, Data/Sequence/Internal.hs
* Add extended introductory information to the module description.
* Experimentally switch to proper mathematics for big-O. Hopefully
people won't complain about the loading speed.
* Tighten the performance bound for `chunksOf`.
=> Rework Data.Sequence documentation

docs/_extensions/HaddockAutolinker.py, docs/map.rst, docs/sequence.rst, docs/set.rst
Implicit links must now start with a slash '/'
Before:
```
:haddock:`Module`        => Not possible
:haddock:`Module#ident`  => current_package/Module#ident
```
After:
```
:haddock:`/Module`       => current_package/Module
:haddock:`/Module#ident` => current_package/Module#ident
```
Previously Module#ident would implicitly link to <package>/Module#ident, but
this prevented implicitly linking to <package>/Module (since its not possible to
differentiate between an explicit Haddock package link or an implicit link
within the current package.
[ci skip]
=> Change syntax for implicit :haddock: autolink.

Data/Sequence/Internal.hs, Data/Sequence/sorting.md
This adds notes on the performance of the pairing heap unstable sorting implementation, and on the performance of a skew heap implementation. The skew heap implementation is slower, so it's described here to save anyone else from duplicating work.
=> Added notes on skew-heap attempt

Data/Sequence.hs, Data/Sequence/Internal.hs, changelog.md
* Add `unzip` and `unzipWith` to `Data.Sequence`.
* Make `unzipWith` *actually* avoid certain space leaks by
ensuring that the result trees are constructed in lock-step.
=> Add unzips for sequences

Data/IntSet/Internal.hs, Utils/Containers/Internal/BitUtil.hs
This utility function will be needed by IntSet.Internal, IntSetValidity, and IntMapValidity.
=> Move bitcount to Utils.Internal.BitUtil.

Data/IntSet.hs, Data/IntSet/Internal.hs, Data/Set.hs, Data/Set/Internal.hs, benchmarks/IntSet.hs, benchmarks/Set.hs, tests/intset-properties.hs, tests/set-properties.hs
This function is equivalent to computing the intersection and checking
if it is empty. However, it is more efficient because the intersection
set does not need to be built in memory, and the computation can
be short-circuited as soon as two non-disjoint `Tip`s are found.
=> Add function to check if two `IntSet`s are `disjoint`.

Data/IntMap/Internal.hs, Data/Map/Internal.hs, benchmarks/IntMap.hs, benchmarks/Map.hs
* Harmonize laziness (not strictness!) of min and max views between
`IntMap` and `Map`.
* Improve GHC's ability to unbox the results of min and max views
for `IntMap`.
Benchmark improvements are tiny, but I think we should do this anyway because it can potentially reduce allocation.
=> Minmaxview fixup

Data/Set.hs
This improves the module level docs for Data.Set following the form of the recent improvements to Data.Sequence. This is for the most part a re-organization of the existing content with a few minor changes so should hopefully be uncontroversial.
Rendered docs can be found [here](http://www.m-renaud.com/haddocks/containers-0.5.10.2/Data-Set.html).
Partially addresses #495.
=> Improve Data.Set module docs.

Data/Containers/ListUtils.hs, containers.cabal, tests/listutils-properties.hs
resolves #439
I think I have the asymptotics for `nubInt` right, but a sanity check wouldn't hurt...
=> add nubOrd and friends

Data/Sequence/Internal.hs, Utils/Containers/Internal/Coercions.hs
So I applied the same techniques in the folds to the traverse, and I got similar speedups. On the multiplyup benchmark: 
```haskell
multiplyUp :: Seq.Seq Int -> Seq.Seq Int
multiplyUp = snd . flip runState 0 . traverse go where
go x = do
s <- State (\x -> (x + 1,x))
return (s * x)
```
On a sequence of length 500000:
```
benchmarking 500000/multiplyUp/new
time                 137.6 ms   (129.7 ms .. 145.7 ms)
0.996 R²   (0.990 R² .. 1.000 R²)
mean                 138.8 ms   (136.4 ms .. 141.4 ms)
std dev              3.470 ms   (2.492 ms .. 4.484 ms)
variance introduced by outliers: 12% (moderately inflated)
benchmarking 500000/multiplyUp/old
time                 355.1 ms   (281.2 ms .. 407.7 ms)
0.995 R²   (0.983 R² .. 1.000 R²)
mean                 339.1 ms   (324.9 ms .. 346.0 ms)
std …
```
=> Faster traverse

Data/Containers/ListUtils.hs, tests/listutils-properties.hs
* Add rewrite rules to allow the nub functions in `ListUtils`
to participate in fold/build fusion.
* For the sake of simplicity, define `nubOrd` and `nubInt` in terms
of `nubOrdOn` and `nubIntOn`.
=> Add RULES for nub functions

Data/IntMap/Lazy.hs, Data/IntMap/Strict.hs, Data/IntSet.hs
Rendered docs can be found at [Data.IntSet](http://www.m-renaud.com/haddocks/containers-0.5.11.0/Data-IntSet.html), [Data.IntMap.Strict](http://www.m-renaud.com/haddocks/containers-0.5.11.0/Data-IntMap-Strict.html), [Data.IntMap.Lazy](http://www.m-renaud.com/haddocks/containers-0.5.11.0/Data-IntMap-Lazy.html).
=> Improve IntSet and IntMap module docs.

Data/Map/Strict.hs
There's no such things as a "strict map", only a Strict API which forces evaluation of values before inserting them into the map.
[ci skip]
=> Remove "strict map" wording from docs

Data/Graph.hs
`Data.Graph` uses a mutable array to track which vertices have
been visited. This was implemented using an `STArray s Vertex Bool`.
This is obviously bad, because the garbage collector will have to
trace the array if it's alive during a collection. Using an unboxed
array instead should always be better. Indeed, doing so will also
dramatically reduce the size of the array, from the number of
vertices in the graph to that divided by the word size. Each array
operation is slightly more complex, but we'll surely win from
memory locality and such anyway.
=> Unbox the `SetM` array

tests/IntMapValidity.hs, tests/IntSetValidity.hs
The previous implementations only checked the `commonPrefix` and `maskRespected`
invariant for the top level Bin constructor and didn't appropriately recurse
into subtrees.
This resolves #522.
=> Fix IntSet and IntMap validity tests (resolves #522).

Data/IntSet.hs, Data/Set.hs
This moves the Construction section to the top and puts all "construction like"
functions under that heading. Also, moves operators out of their own section and
into the appropriate section.
This partially addresses #495.
=> Reorganize Set and IntSet Haddocks.

Data/IntMap/Lazy.hs, Data/IntMap/Strict.hs, Data/Map/Lazy.hs, Data/Map/Strict.hs
**Changes:**
- Move "construction" section to the top
- Include fromList functions in "construction" section
- Remove "operators" section, you don't go "looking for operators", you go
"looking for functionality" which may be available as an operator.
- Move most common query operations (lookup and friends) to the top
- Move partial functions to the bottom of sections.
**Rationale:**
The other approach I considered was that [employed by Data.HashMap](https://hackage.haskell.org/package/unordered-containers-0.2.8.0/docs/Data-HashMap-Strict.html#g:3) which groups the "basic interface" API functions together. I didn't use that approach because I feel it defeats the purpose of an API reference, specifically that all related functions are grouped together. By separating out the "basic …
=> Reorganize Map and IntMap Haddocks.

Data/Graph.hs
Instead of taking the transpose of a graph and then calculating
the outdegree, calculate the indegree directly. This probably
won't actually improve performance much (if at all) until
`base-4.12` or so comes out: see [GHC Trac #14785](https://ghc.haskell.org/trac/ghc/ticket/14785).
If we want, we can reimplement `accumArray` ourselves to work around
this problem.
Fixes #533
=> Speed up indegree

Data/Graph.hs, include/containers.h
* Replace boxed arrays of `Int` with unboxed ones.
* Make a `zipWith` able to fuse.
* Use `fmap` in `outdegree` rather than a custom function for
mapping with an index we don't need anyway.
=> Unbox some more graph stuff

Data/Sequence.hs
In the module header, in a code example where “index” is used infix, the back-ticks need to be escaped, otherwise haddock interprets them as (an alternative form of) quotes for a hyperlinked identifier which in particular makes the back-ticks invisible in the documentation and displays invalid Haskell code in the code example.
=> Fix Documentation Typo in Data/Sequence.hs

Data/Sequence/Internal.hs, changelog.md
Add `Generic` and `Generic1` instances for `Data.Sequence.Internal`
types: `FingerTree`, `Node`, `Elem`, and `Digit`.
=> Add Generic and Generic1 for Seq internals

Data/IntMap/Strict.hs
The documentation describes the arguments as `insertWithKey f key value mp` .
This updates the later referenced argument names to match these.
=> Update documentation for strict insertWithKey.

Data/Map/Internal.hs
The current haddock doesn't type-check.
=> Express `spanAntitone` in terms of `partitionWithKey` instead of `partition`

Data/Tree.hs
The two existing examples could also be implemented using the `Foldable` instance of `Tree`, although I realize that the `Foldable` `maximum` implementation is partial, while the example using `foldTree` is total.
The two additional examples are operations that, as far as I can tell, can't be implemented with `Foldable`, but only with the full catamorphism. This, hopefully, might be compelling examples.
=> Add examples for foldTree

docs/conf.py
The 'sphinx' style changed to have a dull green background colour which is ugly
and more difficult to read. The 'friendly' style has a neutral background and is
nicer to look at (and looks like what the 'sphinx' style used to look like).
=> Switch to using 'friendly' pygments style for docs.

Data/Graph.hs, Data/IntMap/Internal.hs, Data/IntMap/Strict.hs, Data/IntSet/Internal.hs, Data/Map/Internal.hs, Data/Map/Strict/Internal.hs, Data/Set/Internal.hs, Data/Tree.hs
Due to a bug in ghc, some unused imports do not yield warnings.
This commit will remove such unused imports in preparation for
the ghc bug fix (see https://ghc.haskell.org/trac/ghc/ticket/13064).
=> Remove unused imports.

Data/Set/Internal.hs
The previous documentation for Data.Set.unions said that you need a list of sets, 
but the type says that it can be any Foldable structure. `unions :: (Foldable f, Ord a) => f (Set a) -> Set a`.
Changed the wording to `The union of the sets in a Foldable structure`.
(Feel free to change the wording into something better, ofc)
=> Update Data.Set.unions documentation

Data/IntMap/Internal.hs, changelog.md, tests/intmap-properties.hs
As reported in https://github.com/haskell/containers/issues/579 the `Foldable` instance for `IntMap` is unlawful and internally inconsistent. This was caused as a result of the internal representation used by `IntMap`.
More specifically, `fold`, `foldMap`, and `traverse` (via `traverseWithKey`) always placed positively keyed entries before negative keyed ones. To fix this we need to check to see if the mask is positive or negative.
This fixes #579.
Tested by adding new property tests, verifying they failed with the implementation at HEAD, and then passed after the changes. The property tests check that:
- `foldr (:) [] == foldMap (:[])`
- `foldrWithKey (\_ -> (:)) [] == foldMapWithKey (\_ -> (:[]))`
- `getConst (traverse (Const . (:[]))) == getConst (Foldable.traverse_ (Const . (:[])))` …
=> Fix Foldable instance for IntMap (fixes #579)

Data/Set/Internal.hs
If the second argument of `Data.Set.cartesianProduct` happens to
be empty or a singleton, then we don't need to merge a bunch of trees.
So let's not.
=> Speed up special cases of Cartesian products

Data/Containers/ListUtils.hs
* Tighten the performance bounds. The final size of the set is
the number of *distinct* elements in the list, not the total number
of elements.
* Fix missing parenthesis.
* Add example.
=> Improve ListUtils docs

Data/Map/Internal.hs, Data/Set/Internal.hs
* Add recursive size tests to `Data.Set.isSubsetOf`.
* Add a special case for singleton subsets to avoid extra splits
at all the leaves.
Closes #614
=> Improve isSubsetOf

benchmarks/IntMap.hs, benchmarks/IntSet.hs, benchmarks/LookupGE/IntMap.hs, benchmarks/LookupGE/Map.hs, benchmarks/Map.hs, benchmarks/Sequence.hs, benchmarks/Set.hs, benchmarks/SetOperations/SetOperations.hs, containers.cabal, stack.yaml
This removes the circular dependency on ~~criterion~~ containers in the benchmarks.
One consequence of this is that we can now simply use `cabal new-bench`
to run the benchmarks.
=> Replace criterion with gauge as the benchmark framework

Data/Sequence/Internal.hs, changelog.md, tests/seq-properties.hs
Implement `stimes` for sequences using `cycleNTimes`. This makes
it work when the argument is 0 (unlike the default). `cycleNTimes`
is faster and lazier than `stimesMonoid` because it takes advantage
of the finger tree structure of sequences.
Closes #618
=> Implement stimes for sequences

Data/Sequence/Internal.hs, benchmarks/Sequence.hs
Switched NOINLINE to INLINE:
- Ideally this would be INLINABLE, but that can't have phase controls
- This is the next best, which gets the proper performance benefits and also the phase controles so the rewrite rules still fire properly
Because this was prompted by `sequenceA.mapWithIndex` being faster  #603 , a benchamrk of that operation has been added to compare.
Old benchmarks:
```
benchmarking traverseWithIndex/State/10
time                 1.753 μs   (1.705 μs .. 1.841 μs)
0.986 R²   (0.969 R² .. 0.998 R²)
mean                 1.831 μs   (1.760 μs .. 1.998 μs)
std dev              338.5 ns   (141.6 ns .. 623.1 ns)
variance introduced by outliers: 96% (severely inflated)
benchmarking traverseWithIndex/State/100
time                 16.66 μs   (16.40 μs .. 17.00 μs)
0.992 R²   (0.986 …
```
=> Allowed inlining for traverseWithIndex

Data/IntMap/Internal.hs
```
complement (m-1) `xor` m == -m `xor` m
```
Latter produces slightly better assembly.
```asm
movq	%rdi, %rax
negq	%rax
xorq	%rdi, %rax
```
Indeed if we give
```cpp
uint64_t f(uint64_t m_aQU2) {
return ((m_aQU2 - 1) ^ 18446744073709551615UL) ^ m_aQU2;
}
```
to clang and compile with optimisation, that's the ASM it spits out.
Translating it back to Haskell gives the solution from this branch.
Without same optimisation, even in Haskell it saves an instruction.
```hs
maskW :: Word -> Word
maskW m = complement (m-1) `xor` m
{-
movq %rax,%rbx
xorq $-1,%rbx
decq %rax
xorq %rbx,%rax
-}
```
```hs
maskMine :: Word -> Word
maskMine m = (-m) `xor` m
{-
movq %rax,%rbx
negq %rbx
xorq %rax,%rbx
-}
```
=> Produce better code from maskW

Utils/Containers/Internal/BitUtil.hs
Performance may improve after https://gitlab.haskell.org/ghc/ghc/merge_requests/27 but for now I just think that the implementation with `clz` is simpler.
=> Use countLeadingZeros to implement highestBitMask

benchmarks/SetOperations/SetOperations.hs
This avoids issues caused by different benchmarks with the same name.
This fixes #621.
=> Add a running index to set-operations benchmarks.

benchmarks/SetOperations/SetOperations.hs
Benchmarks are now run ordered by method/data_variant/data_size/swapped.
Turns out the output of -l runs sort on the names, so that wasn't obvious until I ran all the benchmarks.
=> Group/Order set-operations-* benchmarks better.

Data/Map/Internal.hs
The Map type has many possible semigroup implementations, so the documentation needs to explain which one was chosen.
=> Document the Semigroup for Map

.travis.yml
The `.travis.yml` isn't meant to be edited by hand anymore.
If you install `haskell-ci` (from the repository), you can
```
haskell-ci --help
```
to see all the options and
```
haskell-ci regenerate --ghc-head
```
to e.g. add some more.
Alternatively you can look for `REGENDATA` in the `.travis.yml` and hand edit it.
---
This PR does exactly what I described, i.e. `haskell-ci regenerate --ghc-head`.
=> Test with ghc-head too

containers/src/Utils/Containers/Internal/BitUtil.hs
GHC requires that boot packages are `-Wall` clean. This fixes an unused import warning and enables `-Werror` to ensure that this doesn't regress again.
=> BitUtil: Fix unused imports

containers/src/Data/IntMap/Internal.hs, containers/src/Data/Map/Internal.hs
The `isProperSubmapOfBy` function takes two maps with different contained value types. Its documentation specifies its behavior in terms of whether the two maps are equal, which is clearly not doable in Haskell. I think it should be specified in terms of whether the two maps have the same keys or not instead.
This tiny commit makes that documentation change.
=> fix documentation of isProperSubmapOfBy

containers-tests/benchmarks/Makefile, containers-tests/tests/Makefile
The `Makefile` for tests uses the same `outputdir` value for all
targets. This interacts badly with ghc's recompilation check:
```
> make bench-IntMap bench-IntSet
ghc -O2 -DTESTING IntMap.hs -I../include -i.. -o bench-IntMap -outputdir tmp -rtsopts
[1 of 1] Compiling Main             ( IntMap.hs, tmp/Main.o )
Linking bench-IntMap ...
ghc -O2 -DTESTING IntSet.hs -I../include -i.. -o bench-IntSet -outputdir tmp -rtsopts
Linking bench-IntSet ...
> ./bench-IntSet --small lookup
lookup                                   mean 218.5 μs  ( +- 1.470 μs  )
> make clean; make bench-IntSet
[...]
> ./bench-IntSet --small lookup
Error: none of the specified names matches a benchmark
Run "bench-IntSet --help" for usage information
> ghc --version
The Glorious Glasgow Haskell Compilation System, version …
```
=> make test Makefiles more robust

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs
The relevant ticket is #654.
I have some supporting material, including more benchmarks, here:
https://gist.github.com/int-e/36578cb04d0a187252c366b0b45ddcb6
=> Improve fromAscList and friends.

containers/src/Data/Tree.hs
The `Forest` type synonym doesn't actually seen to be useful, and it can be confusing (see #440). Stop using it.
=> Stop using the Forest type synonym

containers-tests/tests/intset-properties.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs
This patch fills in the missing piece for Data.IntSet, since Data.{Map,IntMap} and Data.Set all have this function. (for Map variant it's `mapKeysMonotonic`)
=> Add Data.IntSet.mapMonotonic.

containers/src/Data/IntSet/Internal.hs
This is an experiment for `indexOfTheOnlyBit`. I haven't benchmarked yet. But will do so tonight.
=> Use countTrailingZeros for indexOfTheOnlyBit

containers/src/Data/Sequence/Internal/Sorting.hs
The function is self-recursive and not overloaded, therefore I see no reason for the pragma. 
Core lint warns - 
```
*** Core Lint warnings : in result of Simplifier ***
libraries/containers/containers/src/Data/Sequence/Internal/Sorting.hs:389:1: warning:
[RHS of foldToMaybeTree :: forall b a.
(b -> b -> b) -> (a -> b) -> FingerTree a -> Maybe b]
INLINE binder is (non-rule) loop breaker: foldToMaybeTree
```
=> Remove INLINE pragma on foldToMaybeTree

containers-tests/benchmarks/IntSet.hs, containers-tests/tests/intset-properties.hs, containers/src/Data/IntSet/Internal.hs
=> test that instances for Eq and Ord agree with going via toAscList

containers/src/Data/IntSet/Internal.hs
This fixes the build failure I had caused in https://github.com/haskell/containers/pull/697#issuecomment-569939436 (and nearly forgot about).
https://gitlab.haskell.org/sjakobi/ghc/pipelines/14130 shows the result of building GHC with df0905c. I currently assume that the remaining build failures were random flukes. `validate-i386-linux-deb9` notably passed.
Now I'd also like to try to simplify the CPP around imports a bit too.
=> Fix 32-bit build

.gitmodules
This submodule appears to have been erroneously removed in [30ccbaa2].
[30ccbaa2]: https://github.com/haskell/containers/commit/30ccbaa201043109bf1ee905c66ccd0dbe24422f#diff-fc048ebf98a95fc8a8ff9c949d9b49a9.
=> Add haddock-autolink module back in.

.gitignore, containers/src/Data/Map/Internal.hs
deleteFindMin was missing the map argument (`empty`).
=> Fix deleteFindMin Haddock example

.readthedocs.yml
Make previously (grandfathered) ReadTheDocs configuration explicit. This is in
preparation for upgrading to Python 3 which is the default on ReadTheDocs now.
[ci skip]
=> Add readthedocs.yml config file.

.readthedocs.yml
- Update .readthedocs.yml
- Use Python 3 compatible haddock-autolink Sphinx extension.
[ci skip]
=> Upgrade ReadTheDocs to use Python 3.

containers-tests/tests/seq-properties.hs, containers/changelog.md, containers/src/Data/Sequence.hs, containers/src/Data/Sequence/Internal.hs
Make `(<*)` for `Data.Sequence` incrementally asymptotically optimal.
This finally completes the task, begun in December 2014, of making all
the `Applicative` methods for sequences asymptotically optimal
even when their results are consumed incrementally.
Closes #314
=> Reimplement (<*) for sequences

containers/src/Data/Sequence/Internal.hs
Updates the definition of `Monoid (Seq a)` to use canonical definition of `mappend`, allowing https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3174 to pass
=> Data.Sequence.Internal: canonicalise mappend

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
=> Use consistent notation for complexity annotation

containers-tests/containers-tests.cabal, containers/containers.cabal
Hackage now requires `cabal-version >= 1.10`.
=> Bump cabal version

stack.yaml
Previously this command would fail due to circular dependency issues.
Fixes #607, fixes #671.
=> Fix `stack test`

containers/src/Data/Graph.hs
I needed the reverse topological ordering of a graph, so I exposed `revTopSort`. I'm not sure if GHC optimizes away `reverse . reverse` or not.
=> reverse topological ordering

containers-tests/containers-tests.cabal, containers-tests/tests/Utils/IsUnit.hs, containers-tests/tests/intmap-strictness.hs, containers-tests/tests/map-strictness.hs
This is adding some test cases that were previously part of #658.
Note that one test is currently failing because `Data.IntMap.fromAscList` is a bit lazier than expected.
=> add fromList tests

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
…as discussed in
https://github.com/haskell-unordered-containers/unordered-containers/pull/299#discussion_r471089295.
=> Remove strict `compose` versions

containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
Proof:
adjust satisfies
adjust f k m = case lookup k m of
Nothing -> m
Just v  -> insert k (f v) m
and alter satisfies
lookup k (alter f k m) = f (lookup k m)
so
lookup k (adjust f k m)
== case lookup k m of
Nothing -> lookup k m
Just v  -> lookup k (insert k (f v) m)
== case lookup k m of
Nothing -> Nothing
Just v  -> Just (f v)
== fmap f (lookup k m)
== lookup k (alter (fmap f) k m)
== lookup k ((alter . fmap) f k m)
A function is defined by its arguments and a Map is defined by its
lookups, so this suffices to prove that `adjust == alter . fmap`.
=> Note that adjust = alter . fmap in Haddock

containers/src/Data/Sequence/Internal.hs
This fixes a warning generated by `-Woperator-whitespace-ext-conflict`.
Context: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4277
=> Add whitespace in: fmap ($x)

containers/src/Data/Sequence.hs
Perhaps I'm misreading the code here, but I think there's supposed to be a `ys` argument here, right?
=> Add missing `ys` argument to shift2Right

containers/src/Data/Tree.hs
I assume this is an oversight because we do have `Ord1 Tree`.
Some of you may be interested in knowing that I caught this due to trying out the the changes discusssed in the thread that began in https://mail.haskell.org/pipermail/libraries/2020-March/030306.html.
=> Add `Ord (Tree a)` instance.

containers/src/Data/Graph.hs, containers/src/Data/Sequence/Internal.hs
i.e. if it didn't export `Foldable` stuff.
=> Prepare for specialization of Data.List

containers/src/Data/IntSet/Internal.hs
Here's how we fix this without CPP:
In old GHC:
```haskell
I8# :: Int# -> Int8
indexInt8OffAddr# :: Addr# -> Int# -> Int#
```
In upcoming GHC 9.2:
```haskell
I8# :: Int8# -> Int8
indexInt8OffAddr# :: Addr# -> Int# -> Int8#
```
So the "GLB" interface is:
```haskell
exists alpha.
I8# :: alpha -> Int8
indexInt8OffAddr# :: Addr# -> Int# -> alpha
```
We we write a program against that, eliminating the black-box `alpha` with `I8#` and then converting to `Int`.
See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4492
=> Fix for `indexInt8OffAddr#` potentially returning sized type in next GHC

containers-tests/benchmarks/Sequence.hs
=> Use `S.replicate` in sequence-benchmarks

containers/src/Utils/Containers/Internal/PtrEquality.hs
This change allows the `PtrEquality` module to compile with a GHC patch I am preparing ([MR 5932](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5932)) to make `reallyUnsafePtrEquality#` levity-polymorphic.
=> Fix for reallyUnsafePtrEquality# change

containers/src/Data/IntMap.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs
Fixes formatting in `Data.IntMap`/`Data.IntSet` (and related modules).
Due to a line break, the text in quotes was not cursive in the docs, which is fixed by removing the line break.
=> Fix formatting

containers-tests/benchmarks/Map.hs, containers-tests/containers-tests.cabal, containers-tests/tests/Utils/NoThunks.hs, containers-tests/tests/intmap-strictness.hs, containers-tests/tests/intset-strictness.hs, containers-tests/tests/map-strictness.hs, containers-tests/tests/set-properties.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Utils/NoThunks.hs
Fixes #749
There are no tests that checks that `foldr'` or `foldl'` are strict.  The
[nothunks](https://hackage.haskell.org/package/nothunks) library could be used to test it.
- Make Data.Map.foldr' and Data.Map.foldl' more strict
- Make foldrWithKey' and foldlWithKey' more strict
=> Make foldr' & friends more strict

containers/docs/set.rst
In the docs of the overview of Set there is a paragraph on their immutability.
This patch rewrites that paragraph for improved clarity and to fix some
grammatical errors.
=> Rewrite paragraph about set immutability

containers-tests/benchmarks/IntMap.hs, containers-tests/tests/intmap-properties.hs, containers/src/Data/IntMap/Internal.hs
- `IntMap.lookup` no longer checks for short circuit failure.
- Add a new function `IntMap.query` with the old fast-fail behaviour.
Addresses https://github.com/haskell/containers/issues/794
=> Change IntMap.lookup and add new IntMap.query function

containers/include/containers.h
Unboxed arrays are broken on big-endian architectures, see
https://gitlab.haskell.org/ghc/ghc/-/issues/16998 for details.
This patch makes the use of unboxed arrays conditional on
little-endian architecture.
Fixes #673
=> Disable unboxed arrays on big-endian

containers/src/Data/Sequence/Internal.hs
[GHC Proposal #371](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0371-non-magical-eq.md) requires `TypeOperators` to use type equality `a~b`. The following lines are affected:
```
containers/src/Data/Sequence/Internal.hs
4416:instance a ~ Char => IsString (Seq a) where
```
The fix is to simply enable the extension.
=> Enable TypeOperators to use (~)

containers-tests/containers-tests.cabal, containers-tests/tests/seq-properties.hs, containers/changelog.md, containers/containers.cabal, containers/src/Data/Graph.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Data/Tree.hs
* `Data.Sequence`: Add `Lift` instances for `Seq`, `ViewL`, and `ViewR`. The `Seq` instance
tries to be a bit clever about the shape of the resulting tree and the
size of the splice; everything else is straightforward.
* Others: Add `Lift` instances for `Data.IntMap.IntMap`, `Data.IntSet.IntSet`, `Data.Map.Map`, `Data.Set.Set`,
`Data.Tree.Tree`, and `Data.Graph.SCC`.
=> Add Lift instances

containers-tests/benchmarks/LookupGE/LookupGE_IntMap.hs, containers/src/Data/IntMap.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Internal/Debug.hs, containers/src/Data/Map/Lazy.hs, containers/src/Data/Map/Strict.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Sequence.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs
=> Use MathJax format for complexity annotations

.github/workflows/haskell-ci.yml, containers-tests/containers-tests.cabal, containers/containers.cabal
This is just #833 rebased. I couldn't get git to cooperate.
=> Bump CI to GHC 9.0.2 and 9.2.2; reenable benchmarks for GHC 9.2 #833

.github/workflows/haskell-ci.yml, containers-tests/containers-tests.cabal, containers/containers.cabal, containers/src/Data/Graph.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Sequence.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Tree.hs, containers/src/Prelude.hs, containers/src/Utils/Containers/Internal/State.hs
*  Use a private `Prelude` temporarily to deal with warnings arising
from the fact that `liftA2` hasn't always been exposed in the
`Prelude`. Other approaches seemed to involve too much CPP or
required disabling redundant import warnings, which we really don't
want.
* Update CI to test with GHC 9.4 and head.
* Hopefully fix strict fold tests.
=> Prepare for liftA2 being exposed in the Prelude

containers/src/Prelude.hs
Avoid a redundant export
I don't see a warning, but it seems a bit silly to export
`Applicative (..)` explicitly from the custom prelude when
`base >= 4.18.0`. Let's not.
=> Avoid a redundant export

containers/src/Prelude.hs
Relying on base version should work fine, once `base` is bumped. But it currently isn't, causing warnings (again) when compiling ghc. To this end, we can employ this solution, which both avoids this issue, as well as uses less CPP.
=> Use less cpp and don't rely on base version for liftA2 comaptibility

.gitignore
Current .gitignore isn't matching these dirs
```
containers-tests/dist-newstyle/
containers-tests/dist/
containers/dist-newstyle/
containers/dist/
```
=> Fix build paths in gitignore

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal/Debug.hs, containers/src/Data/Set/Internal.hs
CLC has approved the proposal to add `{-# WARNING #-}` to `Data.List.{head,tail}` (https://github.com/haskell/core-libraries-committee/issues/87). It means that usage of `head` and `tail` will emit compile-time warnings.
This patch eliminates all usages of `head` and `tail` in `containers`. They are confined to a couple of debug functions, so should not have any effect on performance or semantics.
=> Avoid `Data.List.{head,tail}`

containers/src/Data/IntMap/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
Between `@`s Haddock requires escaping of special characters like `\`, `<`, `>`. Some code snippets don't have this and the rendered output can be off, sometimes making it [incorrect (`<$>` -> `$`)](https://hackage.haskell.org/package/containers-0.6.5.1/docs/Data-Map-Lazy.html#v:traverseWithKey). This PR fixes the ones I found.
=> Fix some code formatting in docs

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs
Add `takeWhileAntitone`, `dropWhileAntitone` and `spanAntitone` for `IntSet` and `IntMap`.
Fixes #839.
=> Add antitone functions for IntSet and IntMap

containers/note-template-haskell-deps.md, containers/src/Data/Graph.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Data/Tree.hs
Note [ Template Haskell Dependencies ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Modules in containers use DeriveLift in order to give Lift instances for the data types. This is problematic for multi-component sessions which involve loading containers and template-haskell into the same session because
* Lift comes from Language.Haskell.TH.Syntax
* DeriveLift used identifiers from Language.Haskell.TH.Lib.Internal
Therefore the modules add an import on Language.Haskell.TH.Syntax (in order to import Lift) but no dependency is recorded between the module and Language.Haskell.TH.Lib.Internal. However, we need to compile the Internal module before the module in containers as the desugared code for DeriveLift depends on the combinators defined in this module.
Can we fix this in GHC? How about …
=> Add extra implicit dependencies needed by DeriveLift

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers-tests/tests/intmap-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs
Following up from [#874](https://github.com/haskell/containers/pull/874#discussion_r1027248480).
The main changes are using `bin` everywhere and being strict in `IntSet.splitMember`. Also added one missing property test , and benchmarks to measure the change.
IntSet:
```
split:dense:        OK (0.20s)
46.4 ns ± 2.7 ns, 49% less than baseline
split:sparse:       OK (0.18s)
84.2 ns ± 5.5 ns, 41% less than baseline
splitMember:dense:  OK (0.20s)
46.3 ns ± 3.6 ns, 47% less than baseline
splitMember:sparse: OK (0.17s)
82.1 ns ± 5.4 ns, 45% less than baseline
```
IntMap:
```
split:       OK (0.19s)
82.3 ns ± 6.4 ns, 43% less than baseline
splitLookup: OK (0.17s)
84.5 ns ± 5.9 ns, 43% less than baseline
```
=> Faster IntSet and IntMap split functions

containers-tests/benchmarks/Graph.hs, containers-tests/containers-tests.cabal, containers-tests/tests/graph-properties.hs
Tests and benchmarks for the most useful functions in Data.Graph.
This will help evaluate changes like #882.
Benchmarks look like:
```
buildG:            OK (0.72s)
1.32 ms ±  71 μs, 3.0 MB allocated, 984 KB copied,  28 MB peak memory
graphFromEdges:    OK (0.24s)
33.0 ms ± 2.6 ms,  74 MB allocated, 7.1 MB copied,  28 MB peak memory
dfs:               OK (0.32s)
9.88 ms ± 390 μs,  17 MB allocated,  10 MB copied,  28 MB peak memory
dff:               OK (0.61s)
9.41 ms ± 276 μs,  20 MB allocated,  11 MB copied,  28 MB peak memory
topSort:           OK (0.32s)
9.65 ms ± 406 μs,  20 MB allocated,  12 MB copied,  28 MB peak memory
scc:               OK (0.16s)
9.47 ms ± 730 μs,  20 MB allocated,  12 MB copied,  28 MB peak memory
bcc_small:         OK (0.52s)
15.7 ms ± 529 μs,  29 MB …
```
=> Tests and benchmarks for Data.Graph

containers-tests/benchmarks/Tree.hs, containers-tests/containers-tests.cabal, containers-tests/tests/tree-properties.hs, containers/src/Data/Tree.hs
Add some `Foldable` functions for `Data.Tree.Tree`.
* `foldMap`, `null`: Already exist
* `foldr`, `foldl'`: Added, basic functions
* `fold`, `elem`: Added, default definitions but `INLINABLE` helps
* `foldr1`, `foldl1`, `maximum`, `minimum`: Added, default definitions introduce `Maybe`s since these can be partial, we can avoid all that since trees are non-empty.
* `foldMap'`, `toList`, `length`, `sum`, `product`: Not added, defaults work well enough
* `foldr'`, `foldl`: Not added or benchmarked, unlikely to be used(?)
Benchmarks:
```
fold:    OK (0.25s)
15.5 μs ± 962 ns, 85% less than baseline
foldMap: OK (0.14s)
18.0 μs ± 1.7 μs, 82% less than baseline
foldr:   OK (0.18s)
21.8 μs ± 1.5 μs, 93% less than baseline
foldl':  OK (0.30s)
18.1 μs ± 878 ns, 95% less than baseline
foldr1:  OK …
```
=> Faster Tree folds

containers-tests/tests/set-properties.hs
1. Check for validity of the elements of the result, not just the result.
2. Generate sets in the size range we want, rather than potentially splitting a larger one. This is more efficient and also gives us a better shape distribution.
3. Don't bother comparing to a list-based implementation. Once we've performed all the validity checks (which we should have anyway), a size test is sufficient.
=> Improve the test for powerSet

containers-tests/benchmarks/Graph.hs, containers/src/Data/Graph.hs
From #882.
Bundle together `generate`, `prune`, and `chop` into `dfs`.
This eliminates the trees generated by `generate` which significantly reduces time and memory usage.
<details>
<summary>Benchmarks</summary>
On GHC 9.2.5
Before:
<pre>
dfs
n=100,m=1000:       OK (1.19s)
16.7 μs ± 949 ns, 173 KB allocated, 259 B  copied, 299 MB peak memory
n=100,m=10000:      OK (1.00s)
141  μs ± 5.7 μs, 1.6 MB allocated, 2.6 KB copied, 299 MB peak memory
n=10000,m=100000:   OK (3.70s)
12.5 ms ± 136 μs,  17 MB allocated,  13 MB copied, 303 MB peak memory
n=100000,m=1000000: OK (1.67s)
217  ms ± 4.4 ms, 174 MB allocated, 164 MB copied, 325 MB peak memory
dff
n=100,m=1000:       OK (1.20s)
18.5 μs ± 834 ns, 196 KB allocated, 288 B  copied, 325 MB peak memory
n=100,m=10000:      OK (0.79s)
143  μs ±  12 …
=> Optimize Data.Graph.dfs

containers-tests/benchmarks/Graph.hs, containers/src/Data/Graph.hs
Mark `vertices`, `edges`, `buildG`, and `reverseE` as `INLINE`. These are functions with simple definitions that produce or consume lists. Inlining them allows fusion and other optimizations.
<details>
<summary>Benchmarks on GHC 9.2.5</summary>
Before:
<pre>
buildG
n=100,m=1000:       OK (1.33s)
8.14 μs ± 461 ns,  31 KB allocated, 116 B  copied, 216 MB peak memory
n=100,m=10000:      OK (0.87s)
78.3 μs ± 6.2 μs, 239 KB allocated, 6.6 KB copied, 216 MB peak memory
n=10000,m=100000:   OK (0.54s)
1.29 ms ±  99 μs, 2.9 MB allocated, 942 KB copied, 218 MB peak memory
n=100000,m=1000000: OK (0.45s)
34.5 ms ± 2.4 ms,  29 MB allocated,  44 MB copied, 249 MB peak memory
graphFromEdges
n=100,m=1000:       OK (0.71s)
143  μs ±  14 μs, 414 KB allocated, 1.6 KB copied, 299 MB peak memory …
=> Inline simple functions in Data.Graph

containers-tests/benchmarks/Tree.hs, containers-tests/tests/tree-properties.hs, containers/src/Data/Tree.hs
Resolves #906.
<details>
<summary>Benchmarks (GHC 9.2.5)</summary>
Updated some Foldable definitions so it makes sense to check it's not worse.
<pre>
Foldable
fold
bin,n=1000:     OK (1.15s)
3.68 μs ± 225 ns, 13% less than baseline
bin,n=1000000:  OK (0.55s)
8.24 ms ± 694 μs,       same as baseline
line,n=1000:    OK (1.67s)
4.91 μs ± 388 ns,  8% less than baseline
line,n=1000000: OK (0.54s)
14.3 ms ± 886 μs,       same as baseline
foldMap
bin,n=1000:     OK (1.65s)
3.74 μs ± 356 ns, 15% less than baseline
bin,n=1000000:  OK (0.43s)
8.27 ms ± 757 μs,       same as baseline
line,n=1000:    OK (1.67s)
4.96 μs ± 358 ns, 10% less than baseline
line,n=1000000: OK (0.54s)
14.4 ms ± 883 μs, 28% less than baseline
foldr_1
bin,n=1000:     OK (1.70s)
5.24 μs ± 368 ns,       same as baseline …
=> Implement Foldable1 for Data.Tree.Tree

containers-tests/benchmarks/Graph.hs, containers/src/Data/Graph.hs
* Concat difference lists instead of lists to avoid $O(n^2)$ complexity
* Avoid the unnecessary tree labelling step
* Add explanatory comments
I've tried [a few variations](https://gist.github.com/meooow25/bf412acccbb4193d13a4b420e0af326e) and chosen the one which seems best.
Benchmarks on GHC 9.2.5:
Before:
```
bcc
n=100,m=1000:     OK (0.92s)
57.0 μs ± 2.9 μs, 507 KB allocated,  29 B  copied, 216 MB peak memory
n=100,m=10000:    OK (0.25s)
254  μs ±  22 μs, 1.8 MB allocated,  11 KB copied, 216 MB peak memory
n=10000,m=100000: OK (7.64s)
2.526 s ±  96 ms, 3.8 GB allocated, 2.4 GB copied, 1.5 GB peak memory
```
After:
```
bcc
n=100,m=1000:       OK (0.92s)
14.4 μs ± 961 ns,  44 KB allocated,  49 B  copied, 215 MB peak memory, 74% less than baseline
n=100,m=10000:      OK (0.55s)
107  μs ± …
```
=> Optimize Data.Graph.bcc

containers-tests/benchmarks/Graph.hs, containers/src/Data/Graph.hs
Mark functions in Data.Graph that have an Ord constraint as INLINABLE to allow specialization.
Benchmarks on GHC 9.2.5:
The Ord type used in benchmarks is Int.
Before:
```
graphFromEdges
n=100,m=1000:       OK (0.72s)
145  μs ±  11 μs, 414 KB allocated, 1.5 KB copied, 215 MB peak memory
n=100,m=10000:      OK (0.36s)
1.49 ms ± 134 μs, 3.8 MB allocated, 108 KB copied, 215 MB peak memory
n=10000,m=100000:   OK (0.30s)
34.4 ms ± 2.3 ms,  74 MB allocated, 4.4 MB copied, 215 MB peak memory
n=100000,m=1000000: OK (1.83s)
589  ms ±  30 ms, 930 MB allocated,  74 MB copied, 215 MB peak memory
stronglyConnCompR
n=100,m=1000:       OK (0.47s)
185  μs ±  13 μs, 467 KB allocated, 3.6 KB copied, 215 MB peak memory
n=100,m=10000:      OK (0.70s)
1.83 ms ±  88 μs, 4.0 MB allocated, 265 KB copied, 215 MB …
```
=> Allow specialization of Data.Graph functions

containers-tests/containers-tests.cabal, containers-tests/tests/tree-properties.hs, containers/containers.cabal, containers/src/Data/Graph.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Data/Tree.hs, containers/src/Utils/Containers/Internal/Prelude.hs, containers/src/Utils/Containers/Internal/State.hs
* Using a custom prelude named `Prelude` breaks `cabal repl`.  Just rename it, and change imports all over the place.
* Squash a warning about dollar sign use in the test suite.
Fixes #898
=> Rename the custom prelude

containers/src/Data/Graph.hs
*  Add time complexities for `Data.Graph` functions.
*  Avoid the `Forest` synonym as it can be confusing. We stopped using it in `Data.Tree` in #665.
* Document expected input graph properties for `topSort`, `reverseTopSort` and `bcc`.
=> Update Data.Graph documentation

containers/src/Data/Sequence/Internal.hs, containers/src/Data/Tree.hs
* Add `@since` annotations for the `MonadZip` instances for `Data.Sequence` and `Data.Tree`.
* Fix Haddock markup.
=> Minor documentation fixes

containers/src/Data/Graph.hs
Looks like I missed a few of these in a rebase (#923). Unfortunately one is visible in the haddocks, but that ship has sailed.
=> Actually avoid the Forest synonym in Data.Graph

containers-tests/benchmarks/Graph.hs
Add star and line graphs, which are the extremes of wide and deep graphs.
We discussed adding some non-random graphs in #883, here's a couple I think are useful.
<details>
<summary>Benchmarks on GHC 9.2.5</summary>
<pre>
buildG
rand,n=100,m=1000:       OK (4.51s)
7.47 μs ± 332 ns,  30 KB allocated,  98 B  copied, 927 MB peak memory
rand,n=100,m=10000:      OK (7.38s)
99.4 μs ± 3.0 μs, 241 KB allocated, 7.0 KB copied, 927 MB peak memory
rand,n=10000,m=100000:   OK (1.76s)
5.79 ms ± 567 μs, 2.8 MB allocated, 884 KB copied, 927 MB peak memory
rand,n=100000,m=1000000: OK (1.04s)
95.0 ms ± 5.4 ms,  29 MB allocated,  44 MB copied, 938 MB peak memory
star,n=100:              OK (4.90s)
1.43 μs ± 101 ns, 9.4 KB allocated,   6 B  copied, 962 MB peak memory
star,n=1000000:          OK (1.10s)
60.4 …
=> Add more graph types in Graph benchmarks

containers-tests/benchmarks/Graph.hs
Add a maximal DAG in Graph benchmarks. From https://github.com/haskell/containers/pull/931#issuecomment-1427134981.
<details>
<summary>Benchmarks on GHC 9.2.5</summary>
<pre>
buildG
rand,n=100,m=1000:       OK (6.18s)
7.23 μs ± 529 ns,  30 KB allocated, 101 B  copied, 1.1 GB peak memory
rand,n=100,m=10000:      OK (4.66s)
102  μs ± 7.2 μs, 239 KB allocated, 7.1 KB copied, 1.1 GB peak memory
rand,n=10000,m=100000:   OK (2.23s)
5.10 ms ± 486 μs, 2.8 MB allocated, 883 KB copied, 1.1 GB peak memory
rand,n=100000,m=1000000: OK (1.88s)
82.4 ms ± 1.5 ms,  29 MB allocated,  44 MB copied, 1.1 GB peak memory
star,n=100:              OK (6.87s)
1.33 μs ± 109 ns, 9.4 KB allocated,   7 B  copied, 1.2 GB peak memory
star,n=1000000:          OK (1.74s)
59.2 ms ± 1.9 ms,  92 MB allocated,  43 MB copied, …
=> Add a maximal DAG in Graph benchmarks

CONTRIBUTING.md
Added instructions to compile containers-test using symbolic links for Windows users.
=> Using symlinks on Windows to compile containers-tests

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set.hs, containers/src/Data/Set/Internal.hs, containers/src/Data/Tree.hs, containers/src/Utils/Containers/Internal/Prelude.hs
See https://github.com/haskell/core-libraries-committee/issues/167
This is, of course, a bit speculative at the moment, but given that the change does not involve CPP, it should not hurt to merge it early to simplify further impact assessment.
=> Future-proof against potential Prelude.foldl'

containers-tests/benchmarks/Map.hs, containers-tests/benchmarks/Set.hs, containers-tests/tests/map-properties.hs, containers-tests/tests/set-properties.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set/Internal.hs
As discussed in #949, this is a different implementation of the current strategy that is faster and is a good consumer of the input list. However there is an increase in allocations in the no-fusion case.
On GHC 9.2.5:
<details>
<summary>Before</summary>
```
Set
fromDistinctAscList:         OK (0.15s)
37.7 μs ± 2.9 μs, 159 KB allocated, 3.1 KB copied, 8.0 MB peak memory
fromDistinctAscList:fusion:  OK (0.12s)
58.7 μs ± 5.6 μs, 448 KB allocated,  12 KB copied, 8.0 MB peak memory
fromDistinctDescList:        OK (0.16s)
38.1 μs ± 3.6 μs, 159 KB allocated, 3.1 KB copied, 8.0 MB peak memory
fromDistinctDescList:fusion: OK (0.26s)
61.5 μs ± 3.1 μs, 480 KB allocated,  13 KB copied, 8.0 MB peak memory
Map
fromDistinctAscList:         OK (0.18s)
41.1 μs ± 2.8 μs, 191 KB allocated, 4.5 KB copied, …
```
=> Improve {Set,Map}.fromDistinct{Asc,Desc}List

.github/workflows/haskell-ci.yml, cabal.haskell-ci, containers-tests/containers-tests.cabal, containers-tests/tests/map-properties.hs, containers/containers.cabal, containers/src/Data/Graph.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Tree.hs, containers/src/Utils/Containers/Internal/Prelude.hs, containers/src/Utils/Containers/Internal/State.hs
As discussed in https://github.com/haskell/containers/pull/953#issuecomment-1610428490.
=> Drop support of GHC 8.0 and base-4.9

containers/changelog.md, containers/src/Data/Graph.hs
As discussed in #952. 
CC @meooow25
=> Data.Graph.SCC: store mutually reachable vertices in a non-empty list

containers/containers.cabal
=> Bump deepseq bound to allow 1.5

containers/src/Data/Sequence/Internal.hs
"`replicateM` is a sequence counterpart of `replicateM`" doesn't really make much sense, so this PR clarifies it.
=> Clarify replicateM Haddock

containers/src/Data/IntMap/Internal.hs
IntMap.mapKeysMonotonic and IntMap.keysSet take linear time.
=> Fix some IntMap time complexities

containers-tests/benchmarks/IntSet.hs, containers-tests/tests/intset-properties.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs
For #632
Benchmark on GHC 9.2.5:
```
fromRange:       OK (0.20s)
376  ns ±  22 ns, 4.0 KB allocated,   2 B  copied, 7.0 MB peak memory
fromRange:small: OK (0.18s)
10.0 ns ± 872 ps, 119 B  allocated,   0 B  copied, 7.0 MB peak memory
```
Comparing `fromDistinctAscList [1..2^12]` from #951 against `fromRange (1,2^12)`, currently it takes `24.3 μs` (~62x the time) and with fusion it would still take `4.49 μs` (~11x the time).
=> Add Data.IntSet.fromRange

containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set/Internal.hs
As discussed in #870, the complexities for union, difference, etc. on Set and Map were changed in #830 to fix some partiality in the expressions, but along the way new partiality was introduced, and useful special cases like m = 1 get incorrect complexity values from the new formulas.
The original formula was as stated in the original paper:
https://dl.acm.org/doi/10.1145/322123.322127
and this holds for 0 < m <= n, which seems sufficient to me. (The m=0 case is excluded, but for m=0 nothing needs to be done anyway. This contrary to the m=1 case, in which useful work with very specific complexity (namely, O(log(n))) needs to be done.)
This commit reverts all occurrences of the modified complexity formula back to the original one.
NOTE: I have not checked that all functions for which I …
=> Revert union, difference, etc. complexity changes

containers/docs/map.rst, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
This documents the single most common performance mistake when dealing with `containers`.
I have seen professional Haskellers, get it wrong or wonder about it countless times, and the only hint in the entire module space on how the function `f :: a -> a -> a` is applied is on the docs of `insertWith`, which is not where anybody looks when checking the docs of any of these functions.
=> Map/IntMap: Document the most common O(n²) performance mistake

containers/changelog.md, containers/src/Data/IntMap/Internal.hs
All IntMap and IntSet functions taking a key are strict in the key. This allows the Int to be unboxed.
This is technically a breaking change. Currently `split undefined empty = (empty, empty)`, but with this change `split undefined empty = undefined`.
=> Make IntMap split, splitLookup strict in the key

containers/changelog.md, containers/src/Data/IntSet/Internal.hs
Currently, the key is ignored for an empty set.
Similar to #982. I didn't notice it earlier else I would have included it there.
IntSet.split is already strict.
=> Make IntSet splitMember strict in the key

containers/src/Data/IntMap.hs
Recently I had a long discussion elsewhere comparing asymptotics of `IntMap` to balanced binary trees. I think it's worth writing down in the documentation.
=> Elaborate on asymptotics of IntMap

containers-tests/tests/Utils/NoThunks.hs, containers-tests/tests/intmap-strictness.hs, containers-tests/tests/map-strictness.hs, containers/src/Data/Map/Strict/Internal.hs
The `fromDistinctAscList` and `fromDistinctDescList` functions from `Data.Map.Strict` fail to enforce strictness on values.
Consider the following `ghci` session:
```
λ> import qualified Data.Map.Strict as Map
λ> l = Map.elems . Map.fromDistinctAscList . zip ['a'..'f'] $ Just <$> [0::Int ..]
λ> length l
6
λ> :sprint l
l = [Just 0,_,Just 2,_,Just 4,_]
```
The odd-numbered elements are still thunks. This strange behaviour is caused by the two-state algorithm used in the functions. In particular, in `State1` the value isn't forced because the `Push` datatype from the lazy interface is used, and this doesn't have strict fields:
```haskell
next (State1 l stk) (kx, x) = State0 (Push kx x l stk)
```
The solution is to add bangs to the tuple arguments in the `State1` pattern like there are in the …
=> Fix strictness bugs in `fromDistinctAscList` and `fromDistinctDescList`

containers-tests/benchmarks/LookupGE/LookupGE_IntMap.hs, containers-tests/containers-tests.cabal, containers-tests/tests/IntMapValidity.hs, containers-tests/tests/intmap-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs
Replaces the separate `Prefix` and `Mask` fields in the `Bin` constructor with a single field that contains both.
This reduces the memory required by a `Bin` from 5 to 4 words, at the cost of more computations (which are cheap bitwise ops) being necessary for certain operations.
Implements #991 for `IntMap` only. The same can be done for `IntSet` if this is accepted.
Concretely, this reduces the memory required by an `IntMap` by ~12.5% (including the keys and values).
Calculations: For a map with `n` key-values, there are `n` `Tip`s costing 3 words each and `n-1` `Bin`s costing 5 words each before this change and 4 words after. So we save about 1 out of 8 words per key-value.
This PR, in its current state, makes breaking changes to IntMap internals which is reflected in the exports of the …
=> Optimize IntMap.Bin

containers-tests/benchmarks/LookupGE/LookupGE_IntMap.hs, containers-tests/containers-tests.cabal, containers-tests/tests/IntMapValidity.hs, containers-tests/tests/IntSetValidity.hs, containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers/containers.cabal, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/IntSet/Internal/IntTreeCommons.hs
* Replace the separate `Prefix` and `Mask` `Int` fields in the `Bin` constructor with a single `Int` field which contains both merged together. This reduces the memory required by a `Bin` from 5 to 4 words, at the cost of more computations (which are cheap bitwise ops) being necessary for certains operations. This follows a similar change done for `IntMap.Bin` (#995).
* Benchmarks show that runtimes for most operations remain unchanged or decrease by a small amount (<10%). As expected, allocations are consistently lower by 11-16% for all set operations that have to make O(log n) allocations.
* The functions and types used by both `IntSet` and `IntMap` have been moved into a `IntTreeCommons` module.
Fixes #991.
Concretely, this reduces the memory required by an `IntSet` by ~12.5%. …
=> Optimize IntSet.Bin

containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers/src/Data/IntMap/Internal.hs
=> Fix false negatives in IntMap.isProperSubmapOfBy

containers-tests/tests/map-properties.hs, containers/src/Data/Map/Internal.hs
The order of Applicative effects in filterAMissing
was incorrect, causing the order of effects to
differ from key order and be influenced by how
the binary tree was balanced.
The fix is to arrange that effects arising from
the key and value at an internal node come after
those in its left branch instead of before.
(Regardless of this fix such effects come before
those effects arising from the right branch.)
This change also expands test coverage
to detect a regression of this fix.
=> Fix Issue 1004: effect order in filterAMissing

containers/src/Utils/Containers/Internal/PtrEquality.hs
This is unusued today, and triggers an hpc bug by merely existing.
As suggested in https://github.com/haskell/containers/issues/997#issuecomment-2027831451
=> Remove hetPtrEq

containers/changelog.md, containers/src/Data/Graph.hs
This gives a more precise type to the existing `flattenSCC :: SCC a -> [a]`.
Closes #985.
=> Add `flattenSCC1 :: SCC a -> NonEmpty a`

containers-tests/benchmarks/SetOperations/SetOperations-IntMap.hs, containers-tests/benchmarks/SetOperations/SetOperations-IntSet.hs, containers-tests/benchmarks/SetOperations/SetOperations-Map.hs, containers-tests/benchmarks/SetOperations/SetOperations-Set.hs, containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers-tests/tests/map-properties.hs, containers-tests/tests/set-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Lazy.hs, containers/src/Data/Map/Strict.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set.hs, containers/src/Data/Set/Internal.hs
...for Set, Map, IntSet, IntMap. This joins the set operations already implemented: union, intersection, difference.
Closes #1002.
=> Add symmetric difference ops

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs
For both `IntMap` variants, the `<` and `>` did not appear in the haddock output.
While at it, also in the documentation for the other `alterF` variants the `<$>` was turned into a hyperlink.
=> properly markup `<$>` in documentation of `alterF`

containers/src/Data/Map/Internal.hs
`minViewSure`/`maxViewSure` allocates one `MinView`/`MaxView`. This is avoidable, by not having the local `go` function.
https://github.com/haskell/containers/blob/c651094ec026b90c4e9d4ed81bc15eb337d3fc2e/containers/src/Data/Map/Internal.hs#L4017-L4024
<details>
<summary>Core with GHC 9.6</summary>
```
Rec {
-- RHS size: {terms: 38, types: 63, coercions: 0, joins: 0/0}
$wgo6_rpA5
:: forall {k} {a}.
k -> a -> Map k a -> Map k a -> (# k, a, Map k a #)
[GblId[StrictWorker([!, ~, !, !])],
Arity=4,
Str=<1L><L><1L><1L>,
Unf=OtherCon []]
$wgo6_rpA5
= \ (@k_sowX)
(@a_sowY)
(k1_sowZ :: k_sowX)
(x_sox0 :: a_sowY)
(ds_sox1 :: Map k_sowX a_sowY)
(r_sox2 :: Map k_sowX a_sowY) ->
case ds_sox1 of {
Bin bx_dmPX kl_a6HQ xl_a6HR ll_a6HS lr_a6HT ->
case $wgo6_rpA5 @k_sowX @a_sowY kl_a6HQ xl_a6HR ll_a6HS …
```
=> Improve Map minViewSure/maxViewSure

containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
They are redundant because they have the same strictness characteristics as the lazy versions.
=> Delete findWithDefault for Strict Map/IntMap

containers/changelog.md, containers/src/Data/Map/Strict/Internal.hs
mergeWithKey is expected to force the result of applying the combining function.
Fixes #1022.
=> Fix Map.Strict.mergeWithKey strictness

containers/changelog.md, containers/src/Data/IntMap/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
The given functions should be called only on nonempty trees.
Fixes #979.
This could alternately be fixed by changing the docs. I find it slightly better to keep the specification that the user will not receive an empty tree.
=> Fix discrepancy between mergeWithKey impl and docs

containers/changelog.md, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Map/Strict/Internal.hs
Make the functions strict in the first value of the run of equal keys. This makes the strictness match that of the fromList functions.
Fixes #473.
No impact on benchmarks, on GHC 9.6.3
```
Map:
fromAscList: OK
65.2 μs ± 5.4 μs, 686 KB allocated,  21 KB copied, 9.0 MB peak memory,       same as baseline
IntMap:
fromAscList: OK
46.3 μs ± 2.7 μs, 223 KB allocated, 6.1 KB copied,  10 MB peak memory,       same as baseline
```
=> Adjust strictness of from{Asc,Desc}List* for maps

containers-tests/tests/intset-properties.hs, containers/changelog.md, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Set/Internal.hs
I wanted to use `IntSet.lookupMin` today and realized it's not defined. `lookupMin` and `lookupMax` already exist for Set, Map, and IntMap.
Edit: Also
* Update docs for lookupMin, lookupMax, findMin, findMax to be
consistent for all the structures.
* Modify IntMap's lookupMin and lookupMax impls so that Just is
returned immediately and mark them INLINE. This allows GHC to inline
and possibly eliminate the Maybe. Set and Map's lookupMin and
lookupMax are already implemented in this style.
=> Add lookupMin and lookupMax for IntSet

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs
* Add benchmarks
* Mark the function INLINABLE for IntMap. On benchmarks for IntMap Int this reduces the run time by ~22%.
* Remove definitions for (/=). There is no good reason to implement this manually.
Related to #1016.
---
Benchmarks on GHC 9.6.3
```
IntMap before
eq: OK
39.0 μs ± 3.4 μs,   0 B  allocated,   0 B  copied,  10 MB peak memory
IntMap after
eq: OK
30.2 μs ± 3.0 μs,   0 B  allocated,   0 B  copied,  10 MB peak memory, 22% less than baseline
```
=> Update Eq IntSet and Eq (IntMap a)

containers-tests/benchmarks/Map.hs, containers-tests/benchmarks/Set.hs, containers-tests/containers-tests.cabal, containers-tests/tests/map-properties.hs, containers-tests/tests/set-properties.hs, containers/containers.cabal, containers/src/Data/Map/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Utils/Containers/Internal/EqOrdUtil.hs
More efficient implementation moving away from the `toList` based approach.
For #1016.
---
Benchmarks, on GHC 9.6.3:
```
Set before:
eq:      OK
74.9 μs ± 5.6 μs, 447 KB allocated,  86 B  copied, 7.0 MB peak memory
compare: OK
61.9 μs ± 5.9 μs, 447 KB allocated,  85 B  copied, 7.0 MB peak memory
Set after:
eq:      OK
29.2 μs ± 2.7 μs, 128 KB allocated,  11 B  copied, 7.0 MB peak memory, 61% less than baseline
compare: OK
29.1 μs ± 2.8 μs, 128 KB allocated,  11 B  copied, 7.0 MB peak memory, 53% less than baseline
Map before:
eq:      OK
123  μs ±  11 μs, 637 KB allocated, 163 B  copied, 9.0 MB peak memory
compare: OK
168  μs ±  15 μs, 637 KB allocated, 163 B  copied, 9.0 MB peak memory
Map after:
eq:      OK
38.5 μs ± 3.6 μs, 159 KB allocated,  15 B  copied, 9.0 MB peak memory, 68% less …
```
=> More efficient Eq, Ord for Set, Map

containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set/Internal.hs
Uses only the Stack, making FromDistinctMonoState unnecessary. This implementation also allows for quick access to the last element, which may be used in fromAscListWith, mapKeysWith, etc.
Seems to be slightly faster. Benchmarks on GHC 9.6.3:
<details>
<summary>Before</summary>
```
Set
fromDistinctAscList:         OK
21.4 μs ± 1.3 μs, 224 KB allocated, 4.4 KB copied, 8.0 MB peak memory
fromDistinctAscList:fusion:  OK
21.0 μs ± 1.5 μs, 288 KB allocated, 7.6 KB copied, 8.0 MB peak memory
fromDistinctDescList:        OK
21.5 μs ± 840 ns, 224 KB allocated, 4.4 KB copied, 8.0 MB peak memory
fromDistinctDescList:fusion: OK
20.5 μs ± 1.4 μs, 288 KB allocated, 7.9 KB copied, 8.0 MB peak memory
Map
fromDistinctAscList:         OK
28.5 μs ± 2.8 μs, 271 KB allocated, 6.7 KB copied, 9.0 MB peak …
```
=> Simplify fromDistinct{Asc,Desc}List for Set, Map

containers-tests/tests/IntSetValidity.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Utils/Containers/Internal/BitUtil.hs
=> Remove bitcount; use popCount directly

containers/src/Data/IntSet.hs
`Data.IntSet` has an odd section titled "Strictness properties", present for no other module.
Some digging shows that similar sections were removed in #497, #502, #507. Perhaps this was missed.
=> Remove separate strictness section in IntSet docs

containers-tests/containers-tests.cabal, containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers-tests/tests/map-properties.hs, containers-tests/tests/seq-properties.hs
This guards against defining a test or benchmark but forgetting to include it in the test tree.
This was prompted by https://github.com/haskell/containers/pull/972#discussion_r1730341023, but it turns out we already had a couple of mistakenly unused tests.
=> Error on unused-top-binds in tests

containers/src/Data/IntSet/Internal.hs
* This was used for 32-bit GHC, which isn't necessary
* Drop a CPP check for 32/64-bit GHC, GHC doesn't support anything else
Related: #1018
I can't tell why the special case for 32-bit GHC exists. #379 started using the GHC functions but I can't find an explanation for why only on 64-bit. @treeowl do you know?
This PR _should_ improve performance on 32-bit systems, don't know if we want to test that. I don't have a 32-bit system.
=> Remove indexOfTheOnlyBit in IntSet.Internal

containers-tests/tests/intset-properties.hs, containers-tests/tests/set-properties.hs, containers/changelog.md, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Set.hs, containers/src/Data/Set/Internal.hs
* Update Set.intersections to use Foldable1 and be lazier
* Mark definitions INLINABLE for specialization
* Add Intersection and intersections for IntSet
* Add property tests
Fixes #1038
=> Update and export set intersection utilities

.github/workflows/mhs-ci.yml, containers/changelog.md, containers/containers.cabal, containers/include/containers.h, containers/src/Data/Graph.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Data/Tree.hs, containers/src/Utils/Containers/Internal/Prelude.hs, containers/src/Utils/Containers/Internal/StrictMaybe.hs, containers/src/Utils/Containers/Internal/TypeError.hs
Mostly #ifdefs and some type signatures.
=> Various changes to make it compile with MicroHs.

containers-tests/benchmarks/IntSet.hs, containers-tests/benchmarks/Set.hs, containers/changelog.md, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Set/Internal.hs
They are aliases for foldr and have long been documented as deprecated. Similar functions for Map and IntMap were deprecated in 0.5.8.1.
Related: #1044
=> Deprecate Data.Set.fold and Data.IntSet.fold

containers-tests/tests/intset-properties.hs, containers-tests/tests/set-properties.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Set.hs, containers/src/Data/Set/Internal.hs
Using Foldable1 requires a conditional export at the moment, which we want to avoid. We can use Foldable1 once it is available is all base versions we support.
See https://github.com/haskell/containers/pull/1040#issuecomment-2402342165
Related: #1038
=> Use NonEmpty in intersections

containers-tests/benchmarks/Map.hs, containers-tests/benchmarks/Set.hs, containers-tests/tests/map-properties.hs, containers-tests/tests/set-properties.hs
I wrote these up while working on making `fromAscList` fuse well. But I'm seeing some odd behavior there, so I thought I would split this straightforward PR out and work on the rest afterwards.
Current benchmarks on GHC 9.2.5
Set:
```
fromAscList:  OK (0.21s)
50.1 μs ± 2.7 μs, 240 KB allocated, 2.4 KB copied, 8.0 MB peak memory
fromDescList: OK (0.21s)
49.1 μs ± 4.1 μs, 240 KB allocated, 2.4 KB copied, 8.0 MB peak memory
```
Map:
```
fromAscList:         OK
39.6 μs ± 2.7 μs, 343 KB allocated, 5.2 KB copied,  10 MB peak memory
fromAscListWithKey:  OK
47.0 μs ± 4.3 μs, 455 KB allocated,  12 KB copied,  10 MB peak memory
fromDescList:        OK
39.6 μs ± 2.6 μs, 343 KB allocated, 5.5 KB copied,  10 MB peak memory
fromDescListWithKey: OK
48.1 μs ± 3.2 μs, 455 KB allocated,  13 KB copied,  10 …
```
=> Tests and benchmarks for {Set,Map}.fromAscList and friends

containers/changelog.md, containers/src/Data/Graph.hs
The default implementations perform an avoidable list copy for NECyclicSCC. Also
* ~~Implement null, which is always False~~
* Fix flattenSCC being made too lazy accidentally in a previous commit
=> Implement toList and toNonEmpty for SCC

containers-tests/containers-tests.cabal, containers-tests/tests/Utils/ArbitrarySetMap.hs, containers-tests/tests/Utils/Strictness.hs, containers-tests/tests/map-properties.hs, containers-tests/tests/map-strictness.hs, containers-tests/tests/set-properties.hs
For #1019.
Adds a bunch of property tests that try to create strict and lazy `Map`s with bottom values and check if the result map is bottom.
We also need to do `IntMap` but this PR is already huge, will do that later.
=> Strictness tests for Map construction

containers-tests/tests/intmap-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs
=> returning Nil on empty IntMap as done in corresponding functions for Map

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/IntSet/Internal/IntTreeCommons.hs, containers/src/Utils/Containers/Internal/BitUtil.hs
This simplifies the code and the GHC Core. It is not expected to affect
performance since Int-Word conversions are free at runtime.
Additionally,
* Remove the Nat synonym
* Document some preconditions
Closes #1018
=> Remove unnecessary Int-Word conversions

containers-tests/containers-tests.cabal, containers-tests/tests/Utils/MergeFunc.hs, containers-tests/tests/intmap-strictness.hs, containers-tests/tests/map-strictness.hs
=> Add strictness tests for IntMap construction

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers-tests/benchmarks/Map.hs, containers-tests/benchmarks/Sequence.hs, containers-tests/benchmarks/Set.hs, containers-tests/benchmarks/Tree.hs, containers-tests/benchmarks/Utils/Fold.hs, containers-tests/containers-tests.cabal
Define a common set of benchmarks for fold functions, usable for all structures - Set, Map, IntSet, IntMap, Seq, Tree.
=> Add benchmarks for fold functions

containers-tests/containers-tests.cabal, containers-tests/tests/seq-properties.hs, containers/src/Data/Sequence/Internal.hs
This matches the behavior of strict folds on sets and maps.
Closes #1072.
=> Make Seq foldl', foldr' strict in the initial value

containers-tests/benchmarks/Map.hs, containers-tests/benchmarks/Set.hs, containers-tests/benchmarks/SetOperations/SetOperations-Map.hs, containers-tests/benchmarks/SetOperations/SetOperations-Set.hs, containers-tests/benchmarks/Utils/Random.hs, containers-tests/containers-tests.cabal
Trees constructed from [1..n] have a specific structure of perfect
binary trees linked together. We shuffle the list so that the tree
is generated from repeated insertions instead, which forms a random
structure that should be more representative of average use cases.
Most benchmarks show an increase in measured times, the amount varying
from 10% to 80%.
=> Use randomly structured Set and Map in benchmarks

containers-tests/benchmarks/Utils/Fold.hs, containers-tests/tests/intset-properties.hs, containers/changelog.md, containers/src/Data/IntSet/Internal.hs
* Make foldr and foldl short-circuit instead of lazily accumulating thunks.
* Switch to a non-empty style to avoid unnecessary comparisons. This also helps GHC with arity-analysis (somehow), which greatly improves performance of CPS-style foldr and foldl.
* Change the bitwise operations used from ``bitmask = bm .&. -bm; bi = ctz bitmask; bm' = bm `xor` bitmask`` to `bi = ctz bm; bm' = bm .&. (bm-1)` which is slightly faster.
---
Benchmarks with GHC 9.10.1
```
Name                          Time - - - - - - - -    Allocated - - - - -
dense.foldMap_elem            5.6 μs  5.3 μs   -4%      0 B     0 B
dense.foldMap_traverseSum     6.5 μs  4.5 μs  -31%    1.0 KB  1.0 KB   +0%
dense.foldl'_sum              5.6 μs  4.3 μs  -22%      0 B     0 B …
```
=> Improve folds over bits for IntSet

containers-tests/benchmarks/Map.hs, containers-tests/benchmarks/Set.hs, containers/changelog.md, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set/Internal.hs
Make fromAscList, fromAscListWith, fromAscListWithKey more efficient by removing the intermediate list and making them good consumers in list fusion.
Related: #950, #1042
Closes #1032
---
Benchmarks with GHC 9.10.1
Set:
```
Name                   Time - - - - - - - -    Allocated - - - - -
fromAscList             47 μs   19 μs  -59%    240 KB  176 KB  -26%
fromAscList:fusion      88 μs   12 μs  -85%    527 KB  192 KB  -63%
fromDescList            48 μs   19 μs  -61%    240 KB  176 KB  -26%
fromDescList:fusion     90 μs   46 μs  -49%    558 KB  559 KB   +0%
```
Map:
```
Name                          Time - - - - - - - -    Allocated - - - - -
fromAscList                    49 μs   27 μs  -45%    481 KB  209 KB …
```
=> Improve fromAscList and friends for Set and Map 

containers/changelog.md, containers/src/Data/Graph.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Data/Tree.hs
I've added `NFData1` and `NFData2` instances where appropriate for `Data.Graph`, `Data.IntMap`,  `Data.IntSet`, `Data.Map`, `Data.Sequence`, `Data.Set`, `Data.Tree` and relevant internal dependencies
TODO:
Closes #767.
=> NFData1,NFData2 instances (#767)

containers-tests/benchmarks/Map.hs, containers-tests/benchmarks/Set.hs, containers-tests/tests/map-properties.hs, containers/changelog.md, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set/Internal.hs
Use "Builder"s to implement some Set and Map construction functions.
As a result, some have become good consumers in terms of list fusion,
and all are now O(n) for non-decreasing input.
```
Fusible  Fusible  O(n) for     O(n) for
before   after    before       after
Set.fromList         No       Yes      Strict incr  Non-decr
Set.map              -        -        Strict incr  Non-decr
Map.fromList         No       Yes      Strict incr  Non-decr
Map.fromListWith     Yes      Yes      Never        Non-decr
Map.fromListWithKey  Yes      Yes      Never        Non-decr
Map.mapKeys          -        -        Strict incr  Non-decr
Map.mapKeysWith      -        -        Never        Non-decr
```
---
For #1027. Also related to #949.
---
Benchmarks with GHC 9.10.1:
Set:
```
Name …
```
=> Build Set and Map more efficiently and consistently

containers-tests/tests/set-properties.hs, containers/src/Data/IntMap.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Merge/Lazy.hs, containers/src/Data/IntMap/Merge/Strict.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map.hs, containers/src/Data/Map/Merge/Strict.hs, containers/src/Data/Set.hs, containers/src/Data/Set/Internal.hs, containers/src/Utils/Containers/Internal/StrictPair.hs, containers/src/Utils/Containers/Internal/TypeError.hs
It's not necessary to use it for conditional exports or SafeHaskell.
---
The only remaining usages of `TESTING` are in `Sequence.Internal` for alternate `Show` definitions. Existing issue for that: #363.
=> Use the TESTING macro less

containers/docs/map.rst, containers/docs/sequence.rst, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set/Internal.hs
This PR makes a few small grammar fixes within documentation and comments.
In particular, it:
- replaces some instances of the word "lookup" with "look up" when used as a verb;
- inserts the word "the" in places where it is obviously missing;
- changes some instances of "the function" to "this function".
=> Improve documentation grammar and usage.

containers-tests/containers-tests.cabal, containers/changelog.md, containers/src/Data/Map/Internal.hs, containers/src/Data/Set/Internal.hs
Closes #1053
Benchmarks, using GHC 9.10.1:
Set:
<details>
<summary>Expand</summary>
```
Name                            Time - - - - - - - -    Allocated - - - - -
alterF:delete                   845 μs  648 μs  -23%    2.2 MB  2.2 MB   +0%
alterF:four                     1.1 ms  870 μs  -21%    3.1 MB  3.1 MB   +0%
alterF:four:strings             1.8 ms  1.5 ms  -12%    3.1 MB  3.1 MB   +0%
alterF:insert                   938 μs  726 μs  -22%    2.8 MB  2.8 MB   +0%
alterF:member                   945 μs  726 μs  -23%    2.5 MB  2.5 MB   +0%
alterF_naive:four               1.6 ms  1.4 ms  -11%    2.2 MB  2.2 MB   +0%
alterF_naive:four:strings       3.9 ms  3.8 ms   -4%    2.2 MB  2.2 MB   +0%
compare                          37 μs   38 μs   +2% …
```
=> Inline the common case of balance functions

containers/src/Data/Sequence/Internal.hs
There is no reason to export it.
It seems to have been done accidentally (https://github.com/haskell/containers/pull/500#pullrequestreview-90350740).
---
Currently this `State` is the top result for https://hoogle.haskell.org/?hoogle=State. This was confusing for someone who wanted to look up `State`, which is how I became aware of the export.
=> Don't export State from Sequence.Internal

containers/src/Data/Map/Internal.hs, containers/src/Data/Set/Internal.hs
If two non-empty trees are balanced with respect to each other, removing one element from the larger does not take away that property.
=> Skip rebalancing in glue

containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers-tests/tests/map-properties.hs, containers-tests/tests/seq-properties.hs, containers-tests/tests/set-properties.hs
=> More property tests

containers/src/Data/Graph.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Tree.hs, containers/src/Utils/Containers/Internal/State.hs
The default return=pure works and we are long past the Functor-Applicative-Monad Proposal.
=> Remove unnecessary return definitions

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Set/Internal.hs
Haddock preview (the "Warning" line is new):
=> Clear warnings in docs for some construction funcs

containers-tests/containers-tests.cabal, containers/containers.cabal
* Set cabal-version to 2.2
* Set license to the right SPDX identifier
* Drop old -fwarn flags which are included in -Wall (since GHC 9.2)
* Move changelog.md to extra-doc-files
* Add homepage
* Tweak source repo location
=> Modernize the cabal file

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers-tests/tests/intmap-properties.hs, containers/changelog.md, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/IntSet/Internal/IntTreeCommons.hs
Compare the trees directly instead of converting to lists.
The implementation follows broadly the same approach as the previous attempt in commit 7aff529.
Closes #470, closes #787.
Benchmarks with GHC 9.10:
Map
```
Name       Time - - - - - - - -    Allocated - - - - -
A       B     %         A      B     %
compare    167 μs   32 μs  -80%    767 KB    0 B   -100%
```
Set
```
Name              Time - - - - - - - -    Allocated - - - - -
A       B     %         A      B     %
compare:dense      55 μs  412 ns  -99%    640 KB   12 B   -99%
compare:sparse     87 μs   26 μs  -70%    893 KB    0 B   -100%
```
=> Improve compare for IntSet and IntMap

containers/src/Data/Tree.hs
These functions can behave either as depth-first nor breadth-first walks depending on how they are consumed.
Also a bit of punctuation.
=> doc: Remove claim foldTree is depth-first and unfoldTree is breadth-first

containers/changelog.md, containers/containers.cabal
We don't have a good enough reason to expose these modules. They do not offer internals of containers (Set, Map, etc.) and are not required to use other exposed internals.
Closes #1096
=> Don't expose internal util modules

containers/src/Data/Graph.hs
This is to avoid passing around the visited array in dfs' go.
Also add a bang on g, so that dfs is strict in g on non-GHC as it is on GHC.
Closes #1102
---
Core before:
<details>
<summary>Expand</summary>
```
-- RHS size: {terms: 241, types: 183, coercions: 0, joins: 1/6}
$wdfs [InlPrag=[2]]
:: Vertex -> Vertex -> Array# [Vertex] -> [Vertex] -> [Tree Vertex]
[GblId[StrictWorker([!, !, ~, !])],
Arity=4,
Str=<1L><1L><L><1L>,
Unf=OtherCon []]
$wdfs
= \ (ww_sbqZ :: Vertex)
(ww1_sbr0 :: Vertex)
(ww2_sbr2 :: Array# [Vertex])
(vs0_sbr4 :: [Vertex]) ->
runRW#
@LiftedRep
@[Tree Vertex]
(\ (s_aaG5 [OS=OneShot] :: State# RealWorld) ->
case ww_sbqZ of { I# m_iaGP ->
case ww1_sbr0 of { I# n_iaGS ->
join {
$w$j_sbqV [InlPrag=[2], Dmd=1C(1,C(1,L))]
:: Int# -> Int# -> [Tree Vertex] …
```
=> Don't use reader for SetM on GHC

containers/src/Data/IntMap.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs
These were added in 8f6ef9a and are relevant in these other modules too. Also add the missing internal module warning to IntMap.Strict.Internal.
=> Copy IntMap notes to IntMap.{Lazy.Strict} and IntSet

containers/src/Data/IntMap/Internal.hs
So that GHC can optimize it for known functions such as in `sameKeys = liftEq (\_ _ -> True)`.
Fixes #546.
=> Inline liftEq for IntMap

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs
These two exports were removed in 8562003 but there is no strong reason to do so. They remain exported from IntMap.Strict.Internal and the non-internal modules.
See https://github.com/haskell/containers/issues/1059#issuecomment-2676425222
=> Export Key from IntMap.Internal, IntSet.Internal

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs
=> Tighter bounds for IntMap and IntSet merge

.github/workflows/haskell-ci.yml, cabal.project, containers/changelog.md, containers/containers.cabal, containers/src/Data/Graph.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/IntSet/Internal/IntTreeCommons.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs, containers/src/Data/Tree.hs
* Bump version to 0.8
* Update changelog and since annotations
* Update cabal.project to allow CI to work
Closes #1059
=> Prepare for 0.8

containers/containers.cabal
deepseq-1.4.3.0 adds NFData1 and NFData2 which we define instances for.
See https://github.com/haskell/containers/issues/1059#issuecomment-2692904615
=> Bump deepseq to >=1.4.3.0

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs
* Switch to an explicit stack based approach, like we had before 77c8e5f, and like we have for Set and Map today.
* This is a little faster (-13%) on in-memory lists, but much faster (-43%) when list fusion applies because we are now a good consumer. For a dense IntSet in the fusion case it is greatly faster (-81%).
* Avoid a case of undefined behavior in IntMap.fromDistinctAscList due to calling branchMask on equal keys if the caller did not follow the distinct precondition.
* Add property tests for the functions
Closes #951
---
Benchmarks on GHC 9.10.1:
IntSet:
```
Name                         Time - - - - - - - -    Allocated - - - - -
fromAscList                   16 μs   17 μs   +0%    3.6 KB  5.6 KB  +56%
fromAscList:fusion            25 μs …
```
=> Improve Int{Map,Set} construction from asc lists 

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers-tests/containers-tests.cabal, containers-tests/tests/intmap-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs
Also add benchmarks and property tests.
Fixes #288, fixes #842.
This will be the baseline for #1128, I have an implementation in progress.
---
Benchmarks on GHC 9.10.1:
IntSet:
```
Name                          Time - - - - - - - -    Allocated - - - - -
fromList:asc                   45 μs   45 μs   +0%    480 KB  480 KB   +0%
fromList:asc:fusion            56 μs   39 μs  -30%    768 KB  480 KB  -37%
fromList:asc:sparse            94 μs   92 μs   -2%    864 KB  864 KB   +0%
fromList:asc:sparse:fusion    106 μs   84 μs  -20%    1.1 MB  864 KB  -24%
fromList:random               458 μs  463 μs   +1%    1.5 MB  1.5 MB   +0%
fromList:random:fusion        484 μs  448 μs   -7%    1.8 MB  1.5 MB  -17%
```
IntMap:
```
Name                              Time …
```
=> Inline Int{Map,Set}.fromList* for list fusion

containers/src/Data/Set/Internal.hs
Related Issue: #1118
This PR documents the policy for removing duplicate elements in the following functions of `Set`:
- `fromList`
- `fromAscList`
- `fromDescList`
- `map`
=> Document deduplication policy for `Set`.

containers-tests/benchmarks/IntMap.hs, containers/changelog.md, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs
* Properly implement the early return optimization
* No need to have a separate withoutBM
* Remove the unnecessary closure in withoutKeys
* Add some benchmarks
Benchmarks improve by 98% in the dense case which benefits maximally from early return. For the random case, withoutKeys improves by 14% and restrictKeys improves by 20%.
Closes #1130.
---
Benchmarks with GHC 9.10.1
```
Name                   Time - - - - - - - -    Allocated - - - - -
restrictKeys            49 μs  795 ns  -98%    229 KB  4.2 KB  -98%
restrictKeys:random     41 μs   33 μs  -20%     43 KB  6.3 KB  -85%
withoutKeys             21 μs  530 ns  -97%    100 KB   32 B   -99%
withoutKeys:random      55 μs   47 μs  -14%    128 KB  110 KB  -14%
```
=> Improve IntMap's restrictKeys and withoutKeys

containers-tests/tests/intmap-properties.hs, containers-tests/tests/intset-properties.hs, containers/changelog.md, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs
=> Add compareSize for IntSet and IntMap

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs
=> Use binCheck{L,R} where possible

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set/Internal.hs
This is motivated by the proposed removal of mappend from Monoid in the final phase of the Semigroup-Monoid proposal.
We cannot remove mappend references completely yet because we support base-4.10 which is pre-Semigroup-Monoid.
See https://github.com/haskell/core-libraries-committee/issues/328
Related: Redundant `return` definitions were removed in #1095.
=> Guard redundant mappend definitions with CPP

containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntSet.hs, containers/src/Data/IntSet/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Lazy.hs, containers/src/Data/Map/Strict.hs, containers/src/Data/Map/Strict/Internal.hs, containers/src/Data/Sequence/Internal.hs, containers/src/Data/Set.hs, containers/src/Data/Set/Internal.hs
Document partial functions in a consistent manner. Specify the error condition and mention total alternatives, if any.
=> Improve Haddocks for partial functions

containers/src/Data/IntMap/Internal.hs, containers/src/Data/Map/Internal.hs
The words "former" and "latter" in the documentation of `compose` on `IntMap` were swapped. This PR puts them the right way round.
=> Fix haddocks of Data.IntMap.compose

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers-tests/tests/intmap-properties.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs
Implement a fusion-friendly version of the smarter algorithm proposed in #653.
For #1128.
---
Benchmarks on GHC 9.10.1:
IntSet:
```
Name                          Time - - - - - - - -    Allocated - - - - -
fromList:asc                   46 μs   18 μs  -60%    480 KB  5.5 KB  -98%
fromList:asc:fusion            39 μs  4.1 μs  -89%    480 KB  5.5 KB  -98%
fromList:asc:sparse            95 μs   47 μs  -50%    864 KB  352 KB  -59%
fromList:asc:sparse:fusion     87 μs   41 μs  -52%    864 KB  352 KB  -59%
fromList:random               459 μs  467 μs   +1%    1.5 MB  2.4 MB  +67%
fromList:random:fusion        450 μs  459 μs   +1%    1.5 MB  2.4 MB  +67%
fromList:randomDups            57 μs   48 μs  -16%    352 KB  300 KB  -14%
fromList:randomDups:fusion …
```
=> Improve fromList for IntSet and IntMap 

containers/src/Data/Graph.hs
Exporting the constructor but not the selectors was likely an oversight.
=> Export Tree field selectors from Data.Graph

containers-tests/tests/intmap-properties.hs, containers-tests/tests/intmap-strictness.hs, containers-tests/tests/map-properties.hs, containers-tests/tests/map-strictness.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Lazy.hs, containers/src/Data/IntMap/Strict.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/Map/Internal.hs, containers/src/Data/Map/Lazy.hs, containers/src/Data/Map/Strict.hs, containers/src/Data/Map/Strict/Internal.hs
This is the missing member of the group of functions for modifying a single entry.
* adjust takes (a -> a)
* update takes (a -> Maybe a)
* upsert takes (Maybe a -> a)
* alter takes (Maybe a -> Maybe a)
Closes #809.
=> Add upsert for Map and IntMap

containers-tests/benchmarks/Utils/Fold.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntSet/Internal.hs
Move the Nil branch to the top-level and error on Nil in go.
The Note [IntMap folds] added in Data.IntMap.Internal explains the details.
---
Benchmarks on GHC 9.10.1:
IntMap:
```
Name                                  Time - - - - - - - -    Allocated - - - - -
folds with key.foldMap_elem            14 μs   14 μs   +0%     34 B    33 B    -2%
folds with key.foldMap_traverseSum     17 μs   12 μs  -30%     64 KB   42 B   -99%
folds with key.foldl'_maximum          30 μs   18 μs  -41%    128 KB   64 KB  -49%
folds with key.foldl'_sum              12 μs   12 μs   +0%     45 B    44 B    -2%
folds with key.foldl_cpsOneShotSum     36 μs   34 μs   -5%    320 KB  320 KB   +0%
folds with key.foldl_cpsSum            75 μs   34 μs  -54%    608 KB  320 KB  -47% …
```
=> Make Int{Map,Set} folds friendlier to optimizations

containers-tests/benchmarks/IntMap.hs, containers-tests/benchmarks/IntSet.hs, containers/src/Data/IntMap/Internal.hs, containers/src/Data/IntMap/Strict/Internal.hs, containers/src/Data/IntSet/Internal.hs
* Implement the functions in terms of the builders instead of converting to and from a list. This reduces time and allocations.
* Document that they take linear time for monotonic functions.
Closes #1027
---
Benchmarks with GHC 9.10.1:
IntSet:
```
Name            Time - - - - - - - -    Allocated - - - - -
map:asc          36 μs   22 μs  -37%    456 KB  136 KB  -70%
map:random      547 μs  513 μs   -6%    2.9 MB  2.6 MB  -10%
mapMonotonic     35 μs   23 μs  -34%    456 KB  136 KB  -70%
```
IntMap:
```
Name                    Time - - - - - - - -    Allocated - - - - -
mapKeys:asc             101 μs   68 μs  -32%    960 KB  608 KB  -36%
mapKeys:random          594 μs  600 μs   +1%    3.0 MB  2.7 MB  -11% …
```
=> Improve mapping over keys for IntMap and IntSet 

containers/src/Data/Map/Internal.hs, containers/src/Data/Set/Internal.hs
linkL restores balance when the left tree is too heavy for the right tree, but unlike link it skips checking the other way around. linkR handles the opposite. linkL and linkR are used where we know the direction in which we need to rebalance.
linkL and linkR delegate to linkL_ and linkR_, which do the actual work. link also delegates to linkL_ and linkR_, since the direction does not change when linking two trees. This single-direction linking algorithm can be seen in Figure 4 of "Parallel Ordered Sets Using Join". Similarly, link2/merge delegates to link2L_,link2_R/mergeL_,mergeR_.
Benchmarks show a decrease in time and allocations, especially in set-set operations like union. Inspection of the Core of the previous link implementation revealed that it reboxes trees in some cases, which …
=> Add link{L,R} for Set and Map
